
//! Autogenerated weights for pallet_cf_swapping
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-19, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ip-172-31-12-158`, CPU: `Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// /usr/bin/chainflip-node
// benchmark
// pallet
// --pallet
// pallet_cf_swapping
// --extrinsic
// *
// --output
// state-chain/pallets/cf-swapping/src/weights.rs
// --execution=wasm
// --steps=20
// --repeat=10
// --template=state-chain/chainflip-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_cf_swapping.
pub trait WeightInfo {
	fn request_swap_deposit_address() -> Weight;
	fn withdraw() -> Weight;
	fn register_as_broker() -> Weight;
	fn schedule_swap_from_contract() -> Weight;
	fn ccm_deposit() -> Weight;
	fn on_initialize(a: u32, ) -> Weight;
	fn set_swap_ttl() -> Weight;
	fn set_minimum_swap_amount() -> Weight;
	fn set_minimum_ccm_gas_budget() -> Weight;
}

/// Weights for pallet_cf_swapping using the Substrate node and recommended hardware.
pub struct PalletWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for PalletWeight<T> {
	// Storage: AccountRoles AccountRoles (r:1 w:0)
	// Storage: EthereumIngressEgress AddressPool (r:1 w:0)
	// Storage: EthereumIngressEgress ChannelIdCounter (r:1 w:1)
	// Storage: Environment EthereumVaultAddress (r:1 w:0)
	// Storage: Swapping SwapTTL (r:1 w:0)
	// Storage: Swapping SwapChannelExpiries (r:1 w:1)
	// Storage: EthereumIngressEgress DepositAddressDetailsLookup (r:0 w:1)
	// Storage: EthereumIngressEgress ChannelActions (r:0 w:1)
	// Storage: EthereumIngressEgress FetchParamDetails (r:0 w:1)
	// Storage: EthereumIngressEgress AddressStatus (r:0 w:1)
	fn request_swap_deposit_address() -> Weight {
		// Minimum execution time: 94_324 nanoseconds.
		Weight::from_ref_time(95_566_000)
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	// Storage: Environment CurrentSystemState (r:1 w:0)
	// Storage: AccountRoles AccountRoles (r:1 w:0)
	// Storage: Swapping EarnedBrokerFees (r:1 w:1)
	// Storage: EthereumIngressEgress EgressIdCounter (r:1 w:1)
	// Storage: EthereumIngressEgress ScheduledEgressFetchOrTransfer (r:1 w:1)
	fn withdraw() -> Weight {
		// Minimum execution time: 66_669 nanoseconds.
		Weight::from_ref_time(67_866_000)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	// Storage: AccountRoles SwappingEnabled (r:1 w:0)
	// Storage: AccountRoles AccountRoles (r:1 w:1)
	fn register_as_broker() -> Weight {
		// Minimum execution time: 35_607 nanoseconds.
		Weight::from_ref_time(36_191_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Swapping MinimumSwapAmount (r:1 w:0)
	// Storage: Swapping SwapIdCounter (r:1 w:1)
	// Storage: Swapping SwapQueue (r:1 w:1)
	fn schedule_swap_from_contract() -> Weight {
		// Minimum execution time: 36_585 nanoseconds.
		Weight::from_ref_time(37_421_000)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: Swapping MinimumSwapAmount (r:1 w:0)
	// Storage: Swapping MinimumCcmGasBudget (r:1 w:0)
	// Storage: Swapping CcmIdCounter (r:1 w:1)
	// Storage: Swapping SwapIdCounter (r:1 w:1)
	// Storage: Swapping SwapQueue (r:1 w:1)
	// Storage: Swapping CcmOutputs (r:0 w:1)
	// Storage: Swapping PendingCcms (r:0 w:1)
	fn ccm_deposit() -> Weight {
		// Minimum execution time: 51_033 nanoseconds.
		Weight::from_ref_time(51_554_000)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	// Storage: Swapping SwapChannelExpiries (r:1 w:1)
	// Storage: EthereumIngressEgress AddressStatus (r:1 w:0)
	// Storage: EthereumIngressEgress DepositAddressDetailsLookup (r:1 w:1)
	// Storage: EthereumIngressEgress ChannelActions (r:0 w:1)
	/// The range of component `a` is `[1, 100]`.
	fn on_initialize(a: u32, ) -> Weight {
		// Minimum execution time: 49_042 nanoseconds.
		Weight::from_ref_time(23_300_181)
			// Standard Error: 38_614
			.saturating_add(Weight::from_ref_time(22_269_544).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(a.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(a.into())))
	}
	// Storage: Swapping SwapTTL (r:0 w:1)
	fn set_swap_ttl() -> Weight {
		// Minimum execution time: 24_026 nanoseconds.
		Weight::from_ref_time(24_515_000)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Swapping MinimumSwapAmount (r:0 w:1)
	fn set_minimum_swap_amount() -> Weight {
		// Minimum execution time: 25_072 nanoseconds.
		Weight::from_ref_time(25_986_000)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Swapping MinimumCcmGasBudget (r:0 w:1)
	fn set_minimum_ccm_gas_budget() -> Weight {
		// Minimum execution time: 25_656 nanoseconds.
		Weight::from_ref_time(26_422_000)
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: AccountRoles AccountRoles (r:1 w:0)
	// Storage: EthereumIngressEgress AddressPool (r:1 w:0)
	// Storage: EthereumIngressEgress ChannelIdCounter (r:1 w:1)
	// Storage: Environment EthereumVaultAddress (r:1 w:0)
	// Storage: Swapping SwapTTL (r:1 w:0)
	// Storage: Swapping SwapChannelExpiries (r:1 w:1)
	// Storage: EthereumIngressEgress DepositAddressDetailsLookup (r:0 w:1)
	// Storage: EthereumIngressEgress ChannelActions (r:0 w:1)
	// Storage: EthereumIngressEgress FetchParamDetails (r:0 w:1)
	// Storage: EthereumIngressEgress AddressStatus (r:0 w:1)
	fn request_swap_deposit_address() -> Weight {
		// Minimum execution time: 94_324 nanoseconds.
		Weight::from_ref_time(95_566_000)
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(6))
	}
	// Storage: Environment CurrentSystemState (r:1 w:0)
	// Storage: AccountRoles AccountRoles (r:1 w:0)
	// Storage: Swapping EarnedBrokerFees (r:1 w:1)
	// Storage: EthereumIngressEgress EgressIdCounter (r:1 w:1)
	// Storage: EthereumIngressEgress ScheduledEgressFetchOrTransfer (r:1 w:1)
	fn withdraw() -> Weight {
		// Minimum execution time: 66_669 nanoseconds.
		Weight::from_ref_time(67_866_000)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	// Storage: AccountRoles SwappingEnabled (r:1 w:0)
	// Storage: AccountRoles AccountRoles (r:1 w:1)
	fn register_as_broker() -> Weight {
		// Minimum execution time: 35_607 nanoseconds.
		Weight::from_ref_time(36_191_000)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: Swapping MinimumSwapAmount (r:1 w:0)
	// Storage: Swapping SwapIdCounter (r:1 w:1)
	// Storage: Swapping SwapQueue (r:1 w:1)
	fn schedule_swap_from_contract() -> Weight {
		// Minimum execution time: 36_585 nanoseconds.
		Weight::from_ref_time(37_421_000)
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	// Storage: Swapping MinimumSwapAmount (r:1 w:0)
	// Storage: Swapping MinimumCcmGasBudget (r:1 w:0)
	// Storage: Swapping CcmIdCounter (r:1 w:1)
	// Storage: Swapping SwapIdCounter (r:1 w:1)
	// Storage: Swapping SwapQueue (r:1 w:1)
	// Storage: Swapping CcmOutputs (r:0 w:1)
	// Storage: Swapping PendingCcms (r:0 w:1)
	fn ccm_deposit() -> Weight {
		// Minimum execution time: 51_033 nanoseconds.
		Weight::from_ref_time(51_554_000)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(5))
	}
	// Storage: Swapping SwapChannelExpiries (r:1 w:1)
	// Storage: EthereumIngressEgress AddressStatus (r:1 w:0)
	// Storage: EthereumIngressEgress DepositAddressDetailsLookup (r:1 w:1)
	// Storage: EthereumIngressEgress ChannelActions (r:0 w:1)
	/// The range of component `a` is `[1, 100]`.
	fn on_initialize(a: u32, ) -> Weight {
		// Minimum execution time: 49_042 nanoseconds.
		Weight::from_ref_time(23_300_181)
			// Standard Error: 38_614
			.saturating_add(Weight::from_ref_time(22_269_544).saturating_mul(a.into()))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(a.into())))
			.saturating_add(RocksDbWeight::get().writes(1))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(a.into())))
	}
	// Storage: Swapping SwapTTL (r:0 w:1)
	fn set_swap_ttl() -> Weight {
		// Minimum execution time: 24_026 nanoseconds.
		Weight::from_ref_time(24_515_000)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: Swapping MinimumSwapAmount (r:0 w:1)
	fn set_minimum_swap_amount() -> Weight {
		// Minimum execution time: 25_072 nanoseconds.
		Weight::from_ref_time(25_986_000)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: Swapping MinimumCcmGasBudget (r:0 w:1)
	fn set_minimum_ccm_gas_budget() -> Weight {
		// Minimum execution time: 25_656 nanoseconds.
		Weight::from_ref_time(26_422_000)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
