[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build-engine]
description = "Build engine with rename to the dylib"
command = "cargo"
args = ["make", "--profile", "development", "rename-build"]
cwd = "./engine"
workspace = false

[tasks.build-engine-release]
command = "cargo"
args = ["make", "--profile", "release", "rename-build-release"]
cwd = "./engine"
workspace = false

[tasks.build-engine-production]
command = "cargo"
args = ["make", "--profile=production", "rename-build-production"]
cwd = "./engine"
workspace = false

[tasks.build-all]
description = "Builds the specific crate with custom script and the rest of the workspace."
dependencies = ["build-engine"]
command = "cargo"
args = ["build", "--workspace", "--exclude", "engine"]
workspace = false

# Would create a release version of this too
[tasks.build-all-release]
description = "Builds the specific crate with custom script and the rest of the workspace in release mode."
dependencies = ["build-engine-release"]
command = "cargo"
args = ["build", "--release", "--workspace", "--exclude", "engine"]
workspace = false

[tasks.build-all-production]
description = "Builds the specific crate with custom script and the rest of the workspace in production mode."
dependencies = ["build-engine-production"]
command = "cargo"
args = [
    "build",
    "--profile",
    "production",
    "--workspace",
    "--exclude",
    "engine",
]
workspace = false
