[tasks.rename-build]
description = "Runs a custom script after building the crate."
dependencies = ["build"]
command = "sh"
args = ["-c", "./scripts/dylib_version.sh"]

[tasks.build-release]
description = "Builds the crate in release mode."
command = "cargo"
args = ["build", "--release"]

[tasks.rename-build-release]
description = "Runs a custom script after building the crate."
dependencies = ["build-release"]
command = "sh"
args = ["-c", "./scripts/dylib_version.sh"]

[tasks.build-production]
description = "Builds the crate in production mode."
command = "cargo"
args = ["build", "--profile", "production"]

[tasks.rename-build-production]
description = "Runs a custom script after building the crate."
dependencies = ["build-production"]
command = "sh"
args = ["-c", "./scripts/dylib_version.sh"]
