#!/bin/sh
set -e

if [ "$1" != "upgrade" ]; then
    echo "chainflip-node: Fresh install detected, skipping migration"
    exit 0
fi

CF_ROOT=/etc/chainflip

# Stop the service
if systemctl is-active --quiet chainflip-node; then
    echo "Stopping chainflip-node..."
    sudo systemctl stop chainflip-node
    echo "chainflip-node stopped."
else
    echo "chainflip-node is already stopped."
fi

NODE_VERSION=$(chainflip-node -V)

if echo "$NODE_VERSION" | grep 0.8; then
    echo "chainflip-node: Detected version 0.8, skipping migration"
    exit 0
fi

# Backup and delete systemd overrides if they exist
if [ -f /etc/systemd/system/chainflip-node.service.d/override.conf ]; then
    echo "chainflip-node: systemd overrides found - backing up and removing"
    rm -rf /etc/systemd/system/chainflip-node.service.d
fi

# Remove old log files to free space
if [ -f "/var/log/chainflip-node.log" ]; then
    echo "chainflip-node: Removing old log file"
    rm -rf "/var/log/chainflip-node*"
fi

# Purge chaindata
if [ -d $CF_ROOT/chaindata ]; then
    echo "chainflip-node: chaindata found in $CF_ROOT/chaindata - removing"
    rm -rf $CF_ROOT/chaindata
fi

if [ -d $CF_ROOT/data ]; then
    echo "chainflip-node: chaindata found in $CF_ROOT/data - removing"
    rm -rf $CF_ROOT/data
fi

if [ -d $CF_ROOT/chainspecs ]; then
    echo "chainflip-node: chainspecs found in $CF_ROOT/chainspecs - removing"
    rm -rf $CF_ROOT/chainspecs
fi

systemctl daemon-reload

#DEBHELPER#

exit 0
