
// Copyright 2025 Chainflip Labs GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! Autogenerated weights for pallet_cf_witnesser
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.0
//! DATE: 2025-11-28, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `chainflip-benchmark-runner`, CPU: `Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev-3"), DB CACHE: 1024

// Executed Command:
// ./chainflip-node
// benchmark
// pallet
// --pallet
// pallet_cf_witnesser
// --extrinsic
// *
// --output
// state-chain/pallets/cf-witnesser/src/weights.rs
// --steps=20
// --repeat=10
// --template=state-chain/chainflip-weight-template.hbs
// --chain=dev-3

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::ParityDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_cf_witnesser.
pub trait WeightInfo {
	fn witness_at_epoch() -> Weight;
	fn force_witness() -> Weight;
	fn prewitness() -> Weight;
	fn remove_storage_items(n: u32, ) -> Weight;
	fn on_idle_with_nothing_to_remove() -> Weight;
}

/// Weights for pallet_cf_witnesser using the Substrate node and recommended hardware.
pub struct PalletWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for PalletWeight<T> {
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::LastExpiredEpoch` (r:1 w:0)
	/// Proof: `Validator::LastExpiredEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::AuthorityIndex` (r:1 w:0)
	/// Proof: `Validator::AuthorityIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::Votes` (r:1 w:1)
	/// Proof: `Witnesser::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::CallHashExecuted` (r:2 w:1)
	/// Proof: `Witnesser::CallHashExecuted` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::ExtraCallData` (r:1 w:0)
	/// Proof: `Witnesser::ExtraCallData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::WitnessDeadline` (r:1 w:1)
	/// Proof: `Witnesser::WitnessDeadline` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn witness_at_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1700`
		//  Estimated: `7640`
		// Minimum execution time: 55_113_000 picoseconds.
		Weight::from_parts(55_428_000, 7640)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Validator::LastExpiredEpoch` (r:1 w:0)
	/// Proof: `Validator::LastExpiredEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::Votes` (r:1 w:0)
	/// Proof: `Witnesser::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::WitnessDeadline` (r:1 w:1)
	/// Proof: `Witnesser::WitnessDeadline` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::CallHashExecuted` (r:0 w:1)
	/// Proof: `Witnesser::CallHashExecuted` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_witness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `453`
		//  Estimated: `3918`
		// Minimum execution time: 25_775_000 picoseconds.
		Weight::from_parts(26_043_000, 3918)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn prewitness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_308_000 picoseconds.
		Weight::from_parts(5_626_000, 0)
	}
	/// Storage: `Witnesser::Votes` (r:254 w:254)
	/// Proof: `Witnesser::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 255]`.
	fn remove_storage_items(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159 + n * (38 ±0)`
		//  Estimated: `1149 + n * (2513 ±0)`
		// Minimum execution time: 4_816_000 picoseconds.
		Weight::from_parts(3_739_862, 1149)
			// Standard Error: 2_969
			.saturating_add(Weight::from_parts(1_003_512, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2513).saturating_mul(n.into()))
	}
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::LastExpiredEpoch` (r:1 w:0)
	/// Proof: `Validator::LastExpiredEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::WitnessedCallsScheduledForDispatch` (r:1 w:1)
	/// Proof: `Witnesser::WitnessedCallsScheduledForDispatch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::EpochsToCull` (r:1 w:0)
	/// Proof: `Witnesser::EpochsToCull` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn on_idle_with_nothing_to_remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `920`
		//  Estimated: `2405`
		// Minimum execution time: 15_029_000 picoseconds.
		Weight::from_parts(15_650_000, 2405)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::LastExpiredEpoch` (r:1 w:0)
	/// Proof: `Validator::LastExpiredEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::AuthorityIndex` (r:1 w:0)
	/// Proof: `Validator::AuthorityIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::Votes` (r:1 w:1)
	/// Proof: `Witnesser::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::CallHashExecuted` (r:2 w:1)
	/// Proof: `Witnesser::CallHashExecuted` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::ExtraCallData` (r:1 w:0)
	/// Proof: `Witnesser::ExtraCallData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::WitnessDeadline` (r:1 w:1)
	/// Proof: `Witnesser::WitnessDeadline` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn witness_at_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1700`
		//  Estimated: `7640`
		// Minimum execution time: 55_113_000 picoseconds.
		Weight::from_parts(55_428_000, 7640)
			.saturating_add(ParityDbWeight::get().reads(11_u64))
			.saturating_add(ParityDbWeight::get().writes(3_u64))
	}
	/// Storage: `Validator::LastExpiredEpoch` (r:1 w:0)
	/// Proof: `Validator::LastExpiredEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::Votes` (r:1 w:0)
	/// Proof: `Witnesser::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::WitnessDeadline` (r:1 w:1)
	/// Proof: `Witnesser::WitnessDeadline` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::CallHashExecuted` (r:0 w:1)
	/// Proof: `Witnesser::CallHashExecuted` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_witness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `453`
		//  Estimated: `3918`
		// Minimum execution time: 25_775_000 picoseconds.
		Weight::from_parts(26_043_000, 3918)
			.saturating_add(ParityDbWeight::get().reads(4_u64))
			.saturating_add(ParityDbWeight::get().writes(2_u64))
	}
	fn prewitness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_308_000 picoseconds.
		Weight::from_parts(5_626_000, 0)
	}
	/// Storage: `Witnesser::Votes` (r:254 w:254)
	/// Proof: `Witnesser::Votes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 255]`.
	fn remove_storage_items(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159 + n * (38 ±0)`
		//  Estimated: `1149 + n * (2513 ±0)`
		// Minimum execution time: 4_816_000 picoseconds.
		Weight::from_parts(3_739_862, 1149)
			// Standard Error: 2_969
			.saturating_add(Weight::from_parts(1_003_512, 0).saturating_mul(n.into()))
			.saturating_add(ParityDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(ParityDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2513).saturating_mul(n.into()))
	}
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::LastExpiredEpoch` (r:1 w:0)
	/// Proof: `Validator::LastExpiredEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::WitnessedCallsScheduledForDispatch` (r:1 w:1)
	/// Proof: `Witnesser::WitnessedCallsScheduledForDispatch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Witnesser::EpochsToCull` (r:1 w:0)
	/// Proof: `Witnesser::EpochsToCull` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn on_idle_with_nothing_to_remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `920`
		//  Estimated: `2405`
		// Minimum execution time: 15_029_000 picoseconds.
		Weight::from_parts(15_650_000, 2405)
			.saturating_add(ParityDbWeight::get().reads(5_u64))
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
}
