
// Copyright 2025 Chainflip Labs GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! Autogenerated weights for pallet_cf_witnesser
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-05-15, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `chainflip-benchmark-runner`, CPU: `Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev-3"), DB CACHE: 1024

// Executed Command:
// ./chainflip-node
// benchmark
// pallet
// --pallet
// pallet_cf_witnesser
// --extrinsic
// *
// --output
// state-chain/pallets/cf-witnesser/src/weights.rs
// --steps=20
// --repeat=10
// --template=state-chain/chainflip-weight-template.hbs
// --chain=dev-3

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::ParityDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_cf_witnesser.
pub trait WeightInfo {
	fn witness_at_epoch() -> Weight;
	fn force_witness() -> Weight;
	fn prewitness() -> Weight;
	fn remove_storage_items(n: u32, ) -> Weight;
	fn on_idle_with_nothing_to_remove() -> Weight;
}

/// Weights for pallet_cf_witnesser using the Substrate node and recommended hardware.
pub struct PalletWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for PalletWeight<T> {
	fn witness_at_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1805`
		//  Estimated: `0`
		// Minimum execution time: 65_186_000 picoseconds.
		Weight::from_parts(65_710_000, 0)
	}
	fn force_witness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `453`
		//  Estimated: `0`
		// Minimum execution time: 31_077_000 picoseconds.
		Weight::from_parts(31_966_000, 0)
	}
	fn prewitness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_228_000 picoseconds.
		Weight::from_parts(6_541_000, 0)
	}
	/// The range of component `n` is `[1, 255]`.
	fn remove_storage_items(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159 + n * (38 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 5_789_000 picoseconds.
		Weight::from_parts(2_273_509, 0)
			// Standard Error: 3_616
			.saturating_add(Weight::from_parts(1_124_676, 0).saturating_mul(n.into()))
	}
	fn on_idle_with_nothing_to_remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `992`
		//  Estimated: `0`
		// Minimum execution time: 19_361_000 picoseconds.
		Weight::from_parts(19_763_000, 0)
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn witness_at_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1805`
		//  Estimated: `0`
		// Minimum execution time: 65_186_000 picoseconds.
		Weight::from_parts(65_710_000, 0)
	}
	fn force_witness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `453`
		//  Estimated: `0`
		// Minimum execution time: 31_077_000 picoseconds.
		Weight::from_parts(31_966_000, 0)
	}
	fn prewitness() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_228_000 picoseconds.
		Weight::from_parts(6_541_000, 0)
	}
	/// The range of component `n` is `[1, 255]`.
	fn remove_storage_items(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159 + n * (38 ±0)`
		//  Estimated: `0`
		// Minimum execution time: 5_789_000 picoseconds.
		Weight::from_parts(2_273_509, 0)
			// Standard Error: 3_616
			.saturating_add(Weight::from_parts(1_124_676, 0).saturating_mul(n.into()))
	}
	fn on_idle_with_nothing_to_remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `992`
		//  Estimated: `0`
		// Minimum execution time: 19_361_000 picoseconds.
		Weight::from_parts(19_763_000, 0)
	}
}
