#!/bin/sh
set -e

if [ "$1" != "upgrade" ]; then
    echo "chainflip-engine: Fresh install detected, skipping migration"
    exit 0
fi

ENGINE_VERSION=$(chainflip-engine -V)

if echo "$ENGINE_VERSION" | grep 0.9; then
    echo "chainflip-engine: Detected version 0.9, skipping migration"
    exit 0
fi

CF_ROOT=/etc/chainflip

# Stop the service
if systemctl is-active --quiet chainflip-engine; then
    echo "Stopping chainflip-engine..."
    sudo systemctl stop chainflip-engine
    echo "chainflip-engine stopped."
else
    echo "chainflip-engine is already stopped."
fi

# Delete the old engine data.db directory
if [ -d "$CF_ROOT/data.db" ]; then
    echo "chainflip-engine: Removing old data.db directory"
    rm -rf "$CF_ROOT/data.db"
fi

# Backup and delete systemd overrides if they exist
if [ -f /etc/systemd/system/chainflip-engine.service.d/override.conf ]; then
    echo "chainflip-engine: systemd overrides found - backing up and removing"
    rm -rf /etc/systemd/system/chainflip-engine.service.d
fi

# Remove old log files to free space
if [ -f "/var/log/chainflip-engine.log" ]; then
    echo "chainflip-engine: Removing old log file"
    rm -rf "/var/log/chainflip-engine*"
fi

echo "Updating pDOT endpoint ..."
sed -i 's|wss://pdot.chainflip.xyz:443|wss://rpc-pdot.chainflip.io:443|g' /etc/chainflip/config/Settings.toml

FILE=/etc/chainflip/config/Settings.toml
# Check if [dot] section exists
grep -q "\[dot\]" $FILE

if [ $? -eq 0 ]; then
    # [dot] section exists, check if http_node_endpoint exists under [dot]
    grep -q "\[dot\]" -A 1 $FILE | grep -q "http_node_endpoint"

    if [ $? -ne 0 ]; then
        # http_node_endpoint does not exist under [dot], add it
        sed -i '/\[dot\]/a http_node_endpoint = "https://rpc-pdot.chainflip.io:443"' $FILE
        echo "http_node_endpoint key added under [dot]"
    else
        echo "http_node_endpoint key already exists under [dot]"
    fi
else
    echo "[dot] section does not exist in the file"
fi

echo "Migration complete. Restarting chainflip-engine..."

systemctl daemon-reload

#DEBHELPER#

exit 0
