#!/bin/sh
set -e

if [ "$1" != "upgrade" ]; then
    echo "chainflip-engine: Fresh install detected, skipping migration"
    exit 0
fi

# TODO: Uncomment after we re-re-release 0.8
#ENGINE_VERSION=$(chainflip-engine -V)
#
#if echo "$ENGINE_VERSION" | grep 0.8; then
#    echo "chainflip-engine: Detected version 0.8, skipping migration"
#    exit 0
#fi

CF_ROOT=/etc/chainflip

# Stop the service
if systemctl is-active --quiet chainflip-engine; then
    echo "Stopping chainflip-engine..."
    sudo systemctl stop chainflip-engine
    echo "chainflip-engine stopped."
else
    echo "chainflip-engine is already stopped."
fi

# Delete the old engine data.db directory
if [ -d "$CF_ROOT/data.db" ]; then
    echo "chainflip-engine: Removing old data.db directory"
    rm -rf "$CF_ROOT/data.db"
fi

# Backup and delete systemd overrides if they exist
if [ -f /etc/systemd/system/chainflip-engine.service.d/override.conf ]; then
    echo "chainflip-engine: systemd overrides found - backing up and removing"
    rm -rf /etc/systemd/system/chainflip-engine.service.d
fi

# Remove old log files to free space
if [ -f "/var/log/chainflip-engine.log" ]; then
    echo "chainflip-engine: Removing old log file"
    rm -rf "/var/log/chainflip-engine*"
fi

# Add the BTC settings to the config file if they don't exist
if ! grep -q '\[btc\]' /etc/chainflip/config/Settings.toml; then
    echo "chainflip-engine: No BTC config found ... Adding BTC RPC endpoint to config file"
    cat <<EOF >>$CF_ROOT/config/Settings.toml

[btc]
http_node_endpoint = "http://a108a82b574a640359e360cf66afd45d-424380952.eu-central-1.elb.amazonaws.com"
rpc_user = "flip"
rpc_password = "flip"
EOF
fi

# Check if pdot endpoint is pdot.chainflip.io and change to pdot.chainflip.xyz
if grep -q 'pdot.chainflip.io' /etc/chainflip/config/Settings.toml; then
    echo "chainflip-engine: Found pdot.chainflip.io endpoint ... Changing to pdot.chainflip.xyz"
    sed -i 's/pdot.chainflip.io/pdot.chainflip.xyz/g' /etc/chainflip/config/Settings.toml
fi

systemctl daemon-reload

#DEBHELPER#

exit 0
