use std::{collections::HashMap, convert::TryInto};

use crate::{
    eth::key_manager::KeyManager,
    mq::{pin_message_stream, IMQClient, Subject},
    p2p::ValidatorId,
    settings,
    signing::{
        crypto::Signature, KeyId, KeygenOutcome, KeygenSuccess, MessageHash, MessageInfo,
        MultisigEvent, MultisigInstruction, SigningInfo,
    },
    types::chain::Chain,
};

use anyhow::Result;
use futures::StreamExt;
use serde::{Deserialize, Serialize};
use sp_core::Hasher;
use sp_runtime::traits::Keccak256;
use std::str::FromStr;
use web3::{ethabi::Token, types::Address};

use secp256k1::{PublicKey, Secp256k1, SecretKey};

/// Helper function, constructs and runs the [SetAggKeyWithAggKeyEncoder] asynchronously.
pub async fn start<M: IMQClient + Clone>(
    settings: &settings::Settings,
    mq_client: M,
) -> Result<()> {
    let mut encoder = SetAggKeyWithAggKeyEncoder::new(
        settings.eth.key_manager_eth_address.as_ref(),
        settings.signing.genesis_validator_ids.clone(),
        mq_client,
    )?;

    encoder.process_multi_sig_event_stream().await;

    Ok(())
}

/// Details of a transaction to be broadcast to ethereum.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub(super) struct TxDetails {
    pub contract_address: Address,
    pub data: Vec<u8>,
}

// TODO: Use signing::MessageHash once it's updated to use [u8; 32]
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Hash, Eq)]
pub struct FakeMessageHash(pub [u8; 32]);

/// Reads [AuctionConfirmedEvent]s off the message queue and encodes the function call to the stake manager.
#[derive(Clone)]
struct SetAggKeyWithAggKeyEncoder<M: IMQClient> {
    mq_client: M,
    key_manager: KeyManager,
    // maps the MessageHash which gets sent to the signer with the data that the MessageHash is a hash of
    messages: HashMap<FakeMessageHash, ParamContainer>,
    // On genesis, where do these validators come from, to allow for the first key update
    validators: HashMap<KeyId, Vec<ValidatorId>>,
    curr_signing_key_id: Option<u64>,
    next_key_id: Option<u64>,
}

#[derive(Clone)]
struct ParamContainer {
    pub key_id: KeyId,
    pub nonce: [u8; 32],
    pub pubkey_x: [u8; 32],
    pub pubkey_y_parity: u8,
    pub nonce_times_g_addr: [u8; 20],
}

impl<M: IMQClient + Clone> SetAggKeyWithAggKeyEncoder<M> {
    fn new(
        key_manager_address: &str,
        genesis_validator_ids: Vec<ValidatorId>,
        mq_client: M,
    ) -> Result<Self> {
        let key_manager = KeyManager::load(key_manager_address)?;

        let mut genesis_validator_ids_hash_map = HashMap::new();
        genesis_validator_ids_hash_map
            .entry(KeyId(0))
            .or_insert(genesis_validator_ids);
        Ok(Self {
            mq_client,
            key_manager,
            messages: HashMap::new(),
            validators: genesis_validator_ids_hash_map,
            curr_signing_key_id: Some(0),
            next_key_id: None,
        })
    }

    /// Read events from the MultisigEvent subject and process them
    /// The messages we care about are:
    /// 1. `MultisigEvent::KeygenResult` which is emitted after a new key has been
    /// successfully generated by the signing module
    /// 2. `MultisigEvent::MessagedSigned` which is emitted after the Signing module
    /// has successfully signed a message with a particular (denoted by KeyId) key
    async fn process_multi_sig_event_stream(&mut self) {
        let multisig_event_stream = self
            .mq_client
            .subscribe::<MultisigEvent>(Subject::MultisigEvent)
            .await
            .unwrap();

        let mut multisig_event_stream = pin_message_stream(multisig_event_stream);

        while let Some(event) = multisig_event_stream.next().await {
            match event {
                Ok(event) => {
                    match event {
                        MultisigEvent::KeygenResult(key_outcome) => {
                            match key_outcome {
                                KeygenOutcome::Success(keygen_success) => {
                                    self.handle_keygen_success(keygen_success).await;
                                }
                                // TODO: Be more granular with log messages here
                                _ => {
                                    log::error!("Signing module returned error generating key")
                                }
                            }
                        }
                        MultisigEvent::MessageSigned(msg, sig) => {
                            self.handle_set_agg_key_message_signed(msg, sig).await;
                        }
                        _ => {
                            log::trace!("Discarding non keygen result or message signed event")
                        }
                    }
                }
                Err(e) => {
                    log::error!("Error reading event from multisig event stream");
                }
            }
        }
    }

    // When the keygen message has been received we must:
    // 1. Build the ETH encoded setAggKeyWithAggKey transaction parameters
    // 2. Store the tx parameters in state for use later
    // 3. Create a Signing Instruction
    // 4. Push this instruction to the MQ for the signing module to pick up
    fn handle_keygen_success(&mut self, keygen_success: KeygenSuccess) {
        // process the keygensuccess
        let (encoded_fn_params, param_container) = self
            .build_encoded_fn_params(&keygen_success)
            .expect("should be a valid encoded params");

        let hash = Keccak256::hash(&encoded_fn_params[..]);
        let message_hash = FakeMessageHash(hash.into());

        // store key: parameters, so we can fetch the parameters again, after the payload
        // has been signed by the signing module
        self.messages.insert(message_hash.clone(), param_container);

        // Use *all* the validators for now
        let signing_info = SigningInfo::new(curr_signing_key_id.expect("KeyId should be set here"), self.validators);

        let message_hash = MessageHash(message_hash.0.to_vec());
        let signing_instruction = MultisigInstruction::Sign(message_hash, signing_info);

        self.mq_client
            .publish(Subject::MultisigInstruction, &signing_instruction)
            .await
            .expect("Should publish to MQ");
    }

    // When the signed message has been received we must:
    // 1. Get the parameters (`ParameterContainer`) that we stored in state (and submitted to the signing module in encoded form) earlier
    // 2. Build a valid ethereum encoded transaction using the message hash and signature returned by the Signing module
    // 3. Push this transaction to the Broadcast(Chain::ETH) subject, to be broadcast by the ETH Broadcaster
    // 4. Update the current key id, with the new key id returned by the signing module, so we know which key to sign with
    // from now onwards, until the next successful key rotation
    async fn handle_set_agg_key_message_signed(&self, msg: MessageInfo, sig: Signature) {
        // TODO: We can get the key id here from MessageInfo :)

        // 1. Get the data from the message hash that was signed (using the `messages` field)
        let msg: FakeMessageHash = FakeMessageHash(msg.hash.0.try_into().unwrap());
        let params = self
            .messages
            .get(&msg)
            .expect("should have been stored when asked to sign");
        // 2. Call build_tx with the required info
        match self.build_tx(&msg, &sig, params) {
            Ok(ref tx_details) => {
                // 3. Send it on its way to the eth broadcaster
                self.mq_client
                    .publish(Subject::Broadcast(Chain::ETH), tx_details)
                    .await
                    .unwrap_or_else(|err| {
                        log::error!("Could not process: {:#?}", err);
                    });
                // here we assume the key was update successfully
                // update curr key id
                self.curr_signing_key_id = Some(msg.key_id);
                // reset
                self.next_key_id = None;
            }
            Err(err) => {
                log::error!("Failed to build: {:#?}", err);
            }
        }
    }

    fn build_tx(
        &self,
        msg: &FakeMessageHash,
        sig: &Signature,
        params: &ParamContainer,
    ) -> Result<TxDetails> {
        let sig_scalar =
            serde_json::to_string(&sig.sigma).expect("Failed to serialize the sig scalar");
        let sig_scalar: [u8; 32] = sig_scalar.as_bytes().try_into().unwrap();
        let params = [
            Token::Tuple(vec![
                // SigData
                Token::Uint(msg.0.into()),        // msgHash
                Token::Uint(params.nonce.into()), // nonce
                // this 's' / sigma from the `Signature`
                Token::Uint(sig_scalar.into()), // sig
            ]),
            Token::Tuple(vec![
                // Key
                Token::Uint(params.pubkey_x.into()), // pubkeyX
                Token::Uint(params.pubkey_y_parity.into()), // pubkeyYparity
                Token::Address(params.nonce_times_g_addr.into()), // nonceTimesGAddr
            ]),
        ];

        let tx_data = self
            .key_manager
            .set_agg_key_with_agg_key()
            .encode_input(&params[..])?;

        Ok(TxDetails {
            contract_address: self.key_manager.deployed_address,
            data: tx_data.into(),
        })
    }

    fn generate_crypto_parts(
        &self,
        pubkey: secp256k1::PublicKey,
        k_hex: [u8; 32],
    ) -> ([u8; 32], u8, [u8; 20]) {
        // compressed form, means first byte is the y valence
        let pubkey_bytes: [u8; 33] = pubkey.serialize();
        let pubkey_y_parity_byte = pubkey_bytes[0];
        let pubkey_y_parity = if pubkey_y_parity_byte == 2 { 0u8 } else { 1u8 };

        let pubkey_x: [u8; 32] = pubkey_bytes[1..]
            .try_into()
            .expect("should be a valid pubkey");

        let k = SecretKey::from_slice(&k_hex).unwrap();

        let s = Secp256k1::signing_only();

        // this is 'r' -> we should expect this to be the same r as when the sig returns??
        let k_times_g = PublicKey::from_secret_key(&s, &k);

        let k_times_g_pub: [u8; 64] = k_times_g.serialize_uncompressed()[1..]
            .try_into()
            .expect("Should be a valid pubkey");

        // calculate nonce times g addr
        let nonce_times_g_addr = Keccak256::hash(&k_times_g_pub).as_bytes().to_owned();

        // take the last 160bits (20 bytes)
        let from = nonce_times_g_addr.len() - 20;
        let nonce_times_g_addr: [u8; 20] = nonce_times_g_addr[from..]
            .try_into()
            .expect("should only be 20 bytes long");

        // nonce is k
        return (pubkey_x, pubkey_y_parity, nonce_times_g_addr);
    }

    // Temporarily a CFE method, this will be moved to the state chain
    fn build_encoded_fn_params(
        &self,
        keygen_success: &KeygenSuccess,
    ) -> Result<(Vec<u8>, ParamContainer)> {
        let zero = [0u8; 32];

        // generate the nonce, and pass it in to generate_crypto_parts
        // TODO: generate this randomly (crypto-secure)
        // this is "khex" on the smart contract
        let nonce: [u8; 32] =
            hex::decode("d51e13c68bf56155a83e50fd9bc840e2a1847fb9b49cd206a577ecd1cd15e285")
                .unwrap()
                .try_into()
                .unwrap();

        let (pubkey_x, pubkey_y_parity, nonce_times_g_addr) =
            self.generate_crypto_parts(keygen_success.key, nonce);

        let param_container = ParamContainer {
            key_id: keygen_success.key_id,
            nonce,
            pubkey_x,
            pubkey_y_parity,
            nonce_times_g_addr,
        };

        // this payload, gets signed by the CFE signing module
        let params = [
            Token::Tuple(vec![
                // SigData - required for a valid ETH tx
                Token::Uint(zero.into()),  // msgHash
                Token::Uint(zero.into()),  // sig
                Token::Uint(nonce.into()), // nonce
            ]),
            Token::Tuple(vec![
                // New key - the stuff we need to update the key in the KeyManager contract
                Token::Uint(pubkey_x.into()),              // pubkeyX
                Token::Uint(pubkey_y_parity.into()),       // pubkeyYparity
                Token::Address(nonce_times_g_addr.into()), // nonceTimesGAddr
            ]),
        ];

        // Question:
        // This nonce is pushed *encoded* to the signing module. The module is using some
        // "k" to compute the signature, it can't "see into" this encoded eth tx, so how does it
        // sign over with the correct 'k'

        let tx_data = self
            .key_manager
            .set_agg_key_with_agg_key()
            .encode_input(&params[..])?;

        return Ok((tx_data, param_container));
    }
}

// /**
//  * @notice  Set a new aggregate key. Requires a signature from the current aggregate key
//  * @param sigData   The keccak256 hash over the msg (uint) (which is the calldata
//  *                  for this function with empty msgHash and sig) and sig over that hash
//  *                  from the current aggregate key (uint)
//  * @param newKey    The new aggregate key to be set. The x component of the pubkey (uint),
//  *                  the parity of the y component (uint8), and the nonce times G (address)
//  */
// function setAggKeyWithAggKey(
//     SigData calldata sigData,
//     Key calldata newKey
// ) external override nzKey(newKey) validSig(
//     sigData,
//     keccak256(abi.encodeWithSelector(
//         this.setAggKeyWithAggKey.selector,
//         SigData(0, 0, sigData.nonce),
//         newKey
//     )),
//     KeyID.Agg
// ) {
//     emit KeyChange(true, _keyIDToKey[KeyID.Agg], newKey);
//     _keyIDToKey[KeyID.Agg] = newKey;
// }

#[cfg(test)]
mod test_eth_tx_encoder {
    use super::*;
    use hex;

    use crate::mq::mq_mock::MQMock;

    // #[ignore = "Not fully implemented"]
    // #[test]
    // fn test_tx_build() {
    //     let fake_address = hex::encode([12u8; 20]);
    //     let settings = settings::test_utils::new_test_settings().unwrap();
    //     let mq = MQMock::new();

    //     let encoder = SetAggKeyWithAggKeyEncoder::new(
    //         &fake_address[..],
    //         settings.signing.genesis_validator_ids,
    //         mq.get_client(),
    //     )
    //     .expect("Unable to intialise encoder");

    //     let event = FakeNewAggKeySigningComplete {
    //         hash: FakeMessageHash([0; 32]),
    //         sig: [0; 32],
    //     };

    //     let param_container = ParamContainer {
    //         key_id: KeyId(1),
    //         nonce: 3u64,
    //         pubkey_x: [0; 32],
    //         pubkey_y_parity: [0; 32],
    //         nonce_times_g_addr: [0; 20],
    //     };

    //     let _ = encoder
    //         .build_tx(&event, &param_container)
    //         .expect("Unable to encode tx details");
    // }

    // THIS CRYPTO COMES FROM crypto.py in Schnorr from the smart contracts repository
    #[test]
    fn secp256k1_sanity_check() {
        let s = secp256k1::Secp256k1::signing_only();

        let sk = secp256k1::SecretKey::from_str(
            "01010101010101010001020304050607ffff0000ffff00006363636363636363",
        )
        .unwrap();

        let pubkey_from_sk = PublicKey::from_secret_key(&s, &sk);

        // these keys should be derivable from each other.
        let pubkey = secp256k1::PublicKey::from_str(
            "0218845781f631c48f1c9709e23092067d06837f30aa0cd0544ac887fe91ddd166",
        )
        .unwrap();

        // for sanity
        assert_eq!(pubkey_from_sk, pubkey);
    }

    #[test]
    fn test_crypto_parts() {
        let fake_address = hex::encode([12u8; 20]);
        let settings = settings::test_utils::new_test_settings().unwrap();

        let mq = MQMock::new();
        let mq_c = mq.get_client();

        let encoder = SetAggKeyWithAggKeyEncoder::new(
            &fake_address[..],
            settings.signing.genesis_validator_ids,
            mq_c,
        )
        .unwrap();

        let pubkey = secp256k1::PublicKey::from_str(
            "0218845781f631c48f1c9709e23092067d06837f30aa0cd0544ac887fe91ddd166",
        )
        .unwrap();

        encoder.generate_crypto_parts(pubkey);
    }

    // #[test]
    // fn test_build_encodings() {
    //     let fake_address = hex::encode([12u8; 20]);
    //     let settings = settings::test_utils::new_test_settings().unwrap();
    //     let mq = MQMock::new();

    //     let encoder = SetAggKeyWithAggKeyEncoder::new(
    //         &fake_address[..],
    //         settings.signing.genesis_validator_ids,
    //         mq.get_client(),
    //     )
    //     .expect("Unable to intialise encoder");

    //     let event = FakeNewAggKey {
    //         pubkey_x: [0; 32],
    //         pubkey_y_parity: [0; 32],
    //         nonce_times_g_addr: [0; 20],
    //     };

    //     let _ = encoder
    //         .build_encoded_fn_params(&event)
    //         .expect("Unable to encode tx details");
    // }
}
