#!/bin/sh
set -e

if [ "$1" != "upgrade" ]; then
  echo "chainflip-node: Fresh install detected, skipping migration"
  exit 0
fi

CF_ROOT=/etc/chainflip
CF_BKB=$CF_ROOT/bkb

# Stop the service
echo "chainflip-node: Stopping service"
systemctl stop chainflip-node

# Create a backup directory
echo "chainflip-node: Creating backup directory $CF_BKB"
mkdir -p $CF_BKB

# Backup and delete systemd overrides if they exist
if [ -f /etc/systemd/system/chainflip-node.service.d/override.conf ]; then
    echo "chainflip-node: systemd overrides found - backing up and removing"
    mv /etc/systemd/system/chainflip-node.service.d/override.conf $CF_BKB/chainflip-node_override.conf
    rm -rf /etc/systemd/system/chainflip-node.service.d
fi

# Purge chaindata
if [ -d $CF_ROOT/chaindata ]; then
    echo "chainflip-node: chaindata found in $CF_ROOT/chaindata - removing"
    rm -rf $CF_ROOT/chaindata
fi

if [ -d $CF_ROOT/data ]; then
    echo "chainflip-node: chaindata found in $CF_ROOT/data - removing"
    rm -rf $CF_ROOT/data
fi

systemctl daemon-reload
systemctl restart chainflip-node

exit 0
