
// Copyright 2025 Chainflip Labs GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! Autogenerated weights for pallet_cf_broadcast
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.0
//! DATE: 2025-09-11, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `chainflip-benchmark-runner`, CPU: `Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev-3"), DB CACHE: 1024

// Executed Command:
// ./chainflip-node
// benchmark
// pallet
// --pallet
// pallet_cf_broadcast
// --extrinsic
// *
// --output
// state-chain/pallets/cf-broadcast/src/weights.rs
// --steps=20
// --repeat=10
// --template=state-chain/chainflip-weight-template.hbs
// --chain=dev-3

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::ParityDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_cf_broadcast.
pub trait WeightInfo {
	fn update_pallet_config() -> Weight;
	fn on_initialize(t: u32, r: u32, ) -> Weight;
	fn transaction_failed() -> Weight;
	fn on_signature_ready() -> Weight;
	fn start_next_broadcast_attempt() -> Weight;
	fn transaction_succeeded() -> Weight;
	fn stress_test(n: u32, ) -> Weight;
	fn re_sign_aborted_broadcasts(n: u32, ) -> Weight;
}

/// Weights for pallet_cf_broadcast using the Substrate node and recommended hardware.
pub struct PalletWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for PalletWeight<T> {
	/// Storage: `EthereumBroadcaster::BroadcastTimeout` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::BroadcastTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_pallet_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_592_000 picoseconds.
		Weight::from_parts(5_909_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `EthereumChainTracking::CurrentChainState` (r:1 w:0)
	/// Proof: `EthereumChainTracking::CurrentChainState` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `EthereumBroadcaster::Timeouts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::Timeouts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingBroadcasts` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::PendingBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::DelayedBroadcastRetryQueue` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::DelayedBroadcastRetryQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastBarriers` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastBarriers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::AwaitingBroadcast` (r:49 w:49)
	/// Proof: `EthereumBroadcaster::AwaitingBroadcast` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingApiCalls` (r:49 w:0)
	/// Proof: `EthereumBroadcaster::PendingApiCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::CurrentOnChainKey` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::CurrentOnChainKey` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::FailedBroadcasters` (r:49 w:0)
	/// Proof: `EthereumBroadcaster::FailedBroadcasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Reputation::Suspensions` (r:2 w:0)
	/// Proof: `Reputation::Suspensions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastTimeout` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CfeInterface::CfeEvents` (r:1 w:1)
	/// Proof: `CfeInterface::CfeEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::TransactionMetadata` (r:0 w:49)
	/// Proof: `EthereumBroadcaster::TransactionMetadata` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `t` is `[1, 50]`.
	/// The range of component `r` is `[1, 50]`.
	fn on_initialize(t: u32, r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + r * (589 ±0) + t * (115 ±0)`
		//  Estimated: `12230 + r * (2864 ±1) + t * (122 ±1)`
		// Minimum execution time: 35_440_000 picoseconds.
		Weight::from_parts(36_419_000, 12230)
			// Standard Error: 87_057
			.saturating_add(Weight::from_parts(1_113_672, 0).saturating_mul(t.into()))
			// Standard Error: 87_057
			.saturating_add(Weight::from_parts(31_520_090, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 2864).saturating_mul(r.into()))
			.saturating_add(Weight::from_parts(0, 122).saturating_mul(t.into()))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingBroadcasts` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::PendingBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::FailedBroadcasters` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::FailedBroadcasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentAuthorities` (r:1 w:0)
	/// Proof: `Validator::CurrentAuthorities` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::DelayedBroadcastRetryQueue` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::DelayedBroadcastRetryQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transaction_failed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1141`
		//  Estimated: `4606`
		// Minimum execution time: 33_341_000 picoseconds.
		Weight::from_parts(33_975_000, 4606)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `EvmThresholdSigner::SignerAndSignature` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::SignerAndSignature` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastIdToTransactionOutIds` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::BroadcastIdToTransactionOutIds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastBarriers` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastBarriers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumChainTracking::CurrentChainState` (r:1 w:0)
	/// Proof: `EthereumChainTracking::CurrentChainState` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `EthereumBroadcaster::FailedBroadcasters` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::FailedBroadcasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Reputation::Suspensions` (r:2 w:0)
	/// Proof: `Reputation::Suspensions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastTimeout` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::Timeouts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::Timeouts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CfeInterface::CfeEvents` (r:1 w:1)
	/// Proof: `CfeInterface::CfeEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingApiCalls` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::PendingApiCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::TransactionMetadata` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::TransactionMetadata` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::AwaitingBroadcast` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::AwaitingBroadcast` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::TransactionOutIdToBroadcastId` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::TransactionOutIdToBroadcastId` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn on_signature_ready() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1475`
		//  Estimated: `7415`
		// Minimum execution time: 86_302_000 picoseconds.
		Weight::from_parts(87_886_000, 7415)
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `EthereumBroadcaster::PendingBroadcasts` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::PendingBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::AwaitingBroadcast` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::AwaitingBroadcast` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingApiCalls` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::PendingApiCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::CurrentOnChainKey` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::CurrentOnChainKey` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumChainTracking::CurrentChainState` (r:1 w:0)
	/// Proof: `EthereumChainTracking::CurrentChainState` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `EthereumBroadcaster::FailedBroadcasters` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::FailedBroadcasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Reputation::Suspensions` (r:2 w:0)
	/// Proof: `Reputation::Suspensions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastTimeout` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::Timeouts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::Timeouts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CfeInterface::CfeEvents` (r:1 w:1)
	/// Proof: `CfeInterface::CfeEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::TransactionMetadata` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::TransactionMetadata` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn start_next_broadcast_attempt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1780`
		//  Estimated: `7720`
		// Minimum execution time: 63_228_000 picoseconds.
		Weight::from_parts(64_112_000, 7720)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `EthereumBroadcaster::TransactionOutIdToBroadcastId` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::TransactionOutIdToBroadcastId` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingBroadcasts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::PendingBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastBarriers` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastBarriers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::AbortedBroadcasts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::AbortedBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::IncomingKeyAndBroadcastId` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::IncomingKeyAndBroadcastId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::TransactionMetadata` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::TransactionMetadata` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::AwaitingBroadcast` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::AwaitingBroadcast` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::Liabilities` (r:1 w:1)
	/// Proof: `AssetBalances::Liabilities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::RequestSuccessCallbacks` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::RequestSuccessCallbacks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::FailedBroadcasters` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::FailedBroadcasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastIdToTransactionOutIds` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastIdToTransactionOutIds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingApiCalls` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::PendingApiCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transaction_succeeded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1064`
		//  Estimated: `4529`
		// Minimum execution time: 53_834_000 picoseconds.
		Weight::from_parts(54_868_000, 4529)
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `EvmThresholdSigner::CurrentKeyEpoch` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::CurrentKeyEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::Keys` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::Keys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::ThresholdSignatureRequestIdCounter` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::ThresholdSignatureRequestIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Reputation::Suspensions` (r:4 w:0)
	/// Proof: `Reputation::Suspensions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::CeremonyIdCounter` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::CeremonyIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::ThresholdSignatureResponseTimeout` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::ThresholdSignatureResponseTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::CeremonyRetryQueues` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::CeremonyRetryQueues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CfeInterface::CfeEvents` (r:1 w:1)
	/// Proof: `CfeInterface::CfeEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::SignerAndSignature` (r:0 w:50)
	/// Proof: `EvmThresholdSigner::SignerAndSignature` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::PendingCeremonies` (r:0 w:50)
	/// Proof: `EvmThresholdSigner::PendingCeremonies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 50]`.
	fn stress_test(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1051`
		//  Estimated: `11941`
		// Minimum execution time: 53_839_000 picoseconds.
		Weight::from_parts(42_151_963, 11941)
			// Standard Error: 33_524
			.saturating_add(Weight::from_parts(22_247_199, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
	}
	/// Storage: `EthereumBroadcaster::AbortedBroadcasts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::AbortedBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingApiCalls` (r:50 w:0)
	/// Proof: `EthereumBroadcaster::PendingApiCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingBroadcasts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::PendingBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::EthereumSignatureNonce` (r:1 w:1)
	/// Proof: `Environment::EthereumSignatureNonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::EthereumChainId` (r:1 w:0)
	/// Proof: `Environment::EthereumChainId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::EthereumKeyManagerAddress` (r:1 w:0)
	/// Proof: `Environment::EthereumKeyManagerAddress` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumChainTracking::CurrentChainState` (r:1 w:0)
	/// Proof: `EthereumChainTracking::CurrentChainState` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `EvmThresholdSigner::CurrentKeyEpoch` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::CurrentKeyEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::Keys` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::Keys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::ThresholdSignatureRequestIdCounter` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::ThresholdSignatureRequestIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Reputation::Suspensions` (r:4 w:0)
	/// Proof: `Reputation::Suspensions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::CeremonyIdCounter` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::CeremonyIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::ThresholdSignatureResponseTimeout` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::ThresholdSignatureResponseTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::CeremonyRetryQueues` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::CeremonyRetryQueues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CfeInterface::CfeEvents` (r:1 w:1)
	/// Proof: `CfeInterface::CfeEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::SignerAndSignature` (r:0 w:50)
	/// Proof: `EvmThresholdSigner::SignerAndSignature` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::PendingCeremonies` (r:0 w:50)
	/// Proof: `EvmThresholdSigner::PendingCeremonies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::RequestCallback` (r:0 w:50)
	/// Proof: `EvmThresholdSigner::RequestCallback` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 50]`.
	fn re_sign_aborted_broadcasts(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1810 + n * (145 ±0)`
		//  Estimated: `12701 + n * (2621 ±0)`
		// Minimum execution time: 98_100_000 picoseconds.
		Weight::from_parts(47_416_652, 12701)
			// Standard Error: 82_429
			.saturating_add(Weight::from_parts(49_075_069, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(18_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(7_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2621).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `EthereumBroadcaster::BroadcastTimeout` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::BroadcastTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_pallet_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_592_000 picoseconds.
		Weight::from_parts(5_909_000, 0)
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
	/// Storage: `EthereumChainTracking::CurrentChainState` (r:1 w:0)
	/// Proof: `EthereumChainTracking::CurrentChainState` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `EthereumBroadcaster::Timeouts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::Timeouts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingBroadcasts` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::PendingBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::DelayedBroadcastRetryQueue` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::DelayedBroadcastRetryQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastBarriers` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastBarriers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::AwaitingBroadcast` (r:49 w:49)
	/// Proof: `EthereumBroadcaster::AwaitingBroadcast` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingApiCalls` (r:49 w:0)
	/// Proof: `EthereumBroadcaster::PendingApiCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::CurrentOnChainKey` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::CurrentOnChainKey` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::FailedBroadcasters` (r:49 w:0)
	/// Proof: `EthereumBroadcaster::FailedBroadcasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Reputation::Suspensions` (r:2 w:0)
	/// Proof: `Reputation::Suspensions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastTimeout` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CfeInterface::CfeEvents` (r:1 w:1)
	/// Proof: `CfeInterface::CfeEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::TransactionMetadata` (r:0 w:49)
	/// Proof: `EthereumBroadcaster::TransactionMetadata` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `t` is `[1, 50]`.
	/// The range of component `r` is `[1, 50]`.
	fn on_initialize(t: u32, r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + r * (589 ±0) + t * (115 ±0)`
		//  Estimated: `12230 + r * (2864 ±1) + t * (122 ±1)`
		// Minimum execution time: 35_440_000 picoseconds.
		Weight::from_parts(36_419_000, 12230)
			// Standard Error: 87_057
			.saturating_add(Weight::from_parts(1_113_672, 0).saturating_mul(t.into()))
			// Standard Error: 87_057
			.saturating_add(Weight::from_parts(31_520_090, 0).saturating_mul(r.into()))
			.saturating_add(ParityDbWeight::get().reads(8_u64))
			.saturating_add(ParityDbWeight::get().reads((3_u64).saturating_mul(r.into())))
			.saturating_add(ParityDbWeight::get().writes(1_u64))
			.saturating_add(ParityDbWeight::get().writes((2_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 2864).saturating_mul(r.into()))
			.saturating_add(Weight::from_parts(0, 122).saturating_mul(t.into()))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingBroadcasts` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::PendingBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::FailedBroadcasters` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::FailedBroadcasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentAuthorities` (r:1 w:0)
	/// Proof: `Validator::CurrentAuthorities` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::DelayedBroadcastRetryQueue` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::DelayedBroadcastRetryQueue` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transaction_failed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1141`
		//  Estimated: `4606`
		// Minimum execution time: 33_341_000 picoseconds.
		Weight::from_parts(33_975_000, 4606)
			.saturating_add(ParityDbWeight::get().reads(5_u64))
			.saturating_add(ParityDbWeight::get().writes(2_u64))
	}
	/// Storage: `EvmThresholdSigner::SignerAndSignature` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::SignerAndSignature` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastIdToTransactionOutIds` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::BroadcastIdToTransactionOutIds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastBarriers` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastBarriers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumChainTracking::CurrentChainState` (r:1 w:0)
	/// Proof: `EthereumChainTracking::CurrentChainState` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `EthereumBroadcaster::FailedBroadcasters` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::FailedBroadcasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Reputation::Suspensions` (r:2 w:0)
	/// Proof: `Reputation::Suspensions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastTimeout` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::Timeouts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::Timeouts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CfeInterface::CfeEvents` (r:1 w:1)
	/// Proof: `CfeInterface::CfeEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingApiCalls` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::PendingApiCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::TransactionMetadata` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::TransactionMetadata` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::AwaitingBroadcast` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::AwaitingBroadcast` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::TransactionOutIdToBroadcastId` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::TransactionOutIdToBroadcastId` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn on_signature_ready() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1475`
		//  Estimated: `7415`
		// Minimum execution time: 86_302_000 picoseconds.
		Weight::from_parts(87_886_000, 7415)
			.saturating_add(ParityDbWeight::get().reads(12_u64))
			.saturating_add(ParityDbWeight::get().writes(8_u64))
	}
	/// Storage: `EthereumBroadcaster::PendingBroadcasts` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::PendingBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::AwaitingBroadcast` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::AwaitingBroadcast` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingApiCalls` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::PendingApiCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::CurrentOnChainKey` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::CurrentOnChainKey` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumChainTracking::CurrentChainState` (r:1 w:0)
	/// Proof: `EthereumChainTracking::CurrentChainState` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `EthereumBroadcaster::FailedBroadcasters` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::FailedBroadcasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Reputation::Suspensions` (r:2 w:0)
	/// Proof: `Reputation::Suspensions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::CurrentEpoch` (r:1 w:0)
	/// Proof: `Validator::CurrentEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastTimeout` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::Timeouts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::Timeouts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `CfeInterface::CfeEvents` (r:1 w:1)
	/// Proof: `CfeInterface::CfeEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::TransactionMetadata` (r:0 w:1)
	/// Proof: `EthereumBroadcaster::TransactionMetadata` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn start_next_broadcast_attempt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1780`
		//  Estimated: `7720`
		// Minimum execution time: 63_228_000 picoseconds.
		Weight::from_parts(64_112_000, 7720)
			.saturating_add(ParityDbWeight::get().reads(13_u64))
			.saturating_add(ParityDbWeight::get().writes(4_u64))
	}
	/// Storage: `EthereumBroadcaster::TransactionOutIdToBroadcastId` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::TransactionOutIdToBroadcastId` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingBroadcasts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::PendingBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastBarriers` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastBarriers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::AbortedBroadcasts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::AbortedBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::IncomingKeyAndBroadcastId` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::IncomingKeyAndBroadcastId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::TransactionMetadata` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::TransactionMetadata` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::AwaitingBroadcast` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::AwaitingBroadcast` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::Liabilities` (r:1 w:1)
	/// Proof: `AssetBalances::Liabilities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::RequestSuccessCallbacks` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::RequestSuccessCallbacks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::FailedBroadcasters` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::FailedBroadcasters` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::BroadcastIdToTransactionOutIds` (r:1 w:0)
	/// Proof: `EthereumBroadcaster::BroadcastIdToTransactionOutIds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingApiCalls` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::PendingApiCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transaction_succeeded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1064`
		//  Estimated: `4529`
		// Minimum execution time: 53_834_000 picoseconds.
		Weight::from_parts(54_868_000, 4529)
			.saturating_add(ParityDbWeight::get().reads(12_u64))
			.saturating_add(ParityDbWeight::get().writes(7_u64))
	}
	/// Storage: `EvmThresholdSigner::CurrentKeyEpoch` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::CurrentKeyEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::Keys` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::Keys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::ThresholdSignatureRequestIdCounter` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::ThresholdSignatureRequestIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Reputation::Suspensions` (r:4 w:0)
	/// Proof: `Reputation::Suspensions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::CeremonyIdCounter` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::CeremonyIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::ThresholdSignatureResponseTimeout` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::ThresholdSignatureResponseTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::CeremonyRetryQueues` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::CeremonyRetryQueues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CfeInterface::CfeEvents` (r:1 w:1)
	/// Proof: `CfeInterface::CfeEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::SignerAndSignature` (r:0 w:50)
	/// Proof: `EvmThresholdSigner::SignerAndSignature` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::PendingCeremonies` (r:0 w:50)
	/// Proof: `EvmThresholdSigner::PendingCeremonies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 50]`.
	fn stress_test(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1051`
		//  Estimated: `11941`
		// Minimum execution time: 53_839_000 picoseconds.
		Weight::from_parts(42_151_963, 11941)
			// Standard Error: 33_524
			.saturating_add(Weight::from_parts(22_247_199, 0).saturating_mul(n.into()))
			.saturating_add(ParityDbWeight::get().reads(12_u64))
			.saturating_add(ParityDbWeight::get().writes(4_u64))
			.saturating_add(ParityDbWeight::get().writes((2_u64).saturating_mul(n.into())))
	}
	/// Storage: `EthereumBroadcaster::AbortedBroadcasts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::AbortedBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingApiCalls` (r:50 w:0)
	/// Proof: `EthereumBroadcaster::PendingApiCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumBroadcaster::PendingBroadcasts` (r:1 w:1)
	/// Proof: `EthereumBroadcaster::PendingBroadcasts` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::EthereumSignatureNonce` (r:1 w:1)
	/// Proof: `Environment::EthereumSignatureNonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::EthereumChainId` (r:1 w:0)
	/// Proof: `Environment::EthereumChainId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::EthereumKeyManagerAddress` (r:1 w:0)
	/// Proof: `Environment::EthereumKeyManagerAddress` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EthereumChainTracking::CurrentChainState` (r:1 w:0)
	/// Proof: `EthereumChainTracking::CurrentChainState` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `EvmThresholdSigner::CurrentKeyEpoch` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::CurrentKeyEpoch` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::Keys` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::Keys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::ThresholdSignatureRequestIdCounter` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::ThresholdSignatureRequestIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Validator::HistoricalAuthorities` (r:1 w:0)
	/// Proof: `Validator::HistoricalAuthorities` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Reputation::Suspensions` (r:4 w:0)
	/// Proof: `Reputation::Suspensions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::CeremonyIdCounter` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::CeremonyIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::ThresholdSignatureResponseTimeout` (r:1 w:0)
	/// Proof: `EvmThresholdSigner::ThresholdSignatureResponseTimeout` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::CeremonyRetryQueues` (r:1 w:1)
	/// Proof: `EvmThresholdSigner::CeremonyRetryQueues` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `CfeInterface::CfeEvents` (r:1 w:1)
	/// Proof: `CfeInterface::CfeEvents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::SignerAndSignature` (r:0 w:50)
	/// Proof: `EvmThresholdSigner::SignerAndSignature` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::PendingCeremonies` (r:0 w:50)
	/// Proof: `EvmThresholdSigner::PendingCeremonies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EvmThresholdSigner::RequestCallback` (r:0 w:50)
	/// Proof: `EvmThresholdSigner::RequestCallback` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 50]`.
	fn re_sign_aborted_broadcasts(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1810 + n * (145 ±0)`
		//  Estimated: `12701 + n * (2621 ±0)`
		// Minimum execution time: 98_100_000 picoseconds.
		Weight::from_parts(47_416_652, 12701)
			// Standard Error: 82_429
			.saturating_add(Weight::from_parts(49_075_069, 0).saturating_mul(n.into()))
			.saturating_add(ParityDbWeight::get().reads(18_u64))
			.saturating_add(ParityDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(ParityDbWeight::get().writes(7_u64))
			.saturating_add(ParityDbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2621).saturating_mul(n.into()))
	}
}
