
//! Autogenerated weights for pallet_cf_reputation
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-09-28, STEPS: [50, ], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Interpreted, CHAIN: None, DB CACHE: 128

// Executed Command:
// ./target/release/state-chain-node
// benchmark
// --extrinsic
// *
// --pallet
// pallet_cf_reputation
// --output
// state-chain/runtime/src/weights
// --execution=wasm
// --steps=50
// --repeat=20


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for pallet_cf_reputation.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_cf_reputation::WeightInfo for WeightInfo<T> {
	fn heartbeat(b: u32, ) -> Weight {
		(128_854_000 as Weight)
			// Standard Error: 6_000
			.saturating_add((52_000 as Weight).saturating_mul(b as Weight))
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	fn on_initialize(x: u32, ) -> Weight {
		(17_445_698_000 as Weight)
			// Standard Error: 1_275_000
			.saturating_add((168_900_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(T::DbWeight::get().reads(366 as Weight))
			.saturating_add(T::DbWeight::get().writes(365 as Weight))
	}
	fn update_accrual_ratio(b: u32, ) -> Weight {
		(61_639_000 as Weight)
			// Standard Error: 1_000
			.saturating_add((5_000 as Weight).saturating_mul(b as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
