#!/usr/bin/env -S pnpm tsx

import { PublicKey } from '@solana/web3.js';
import { decodeSolAddress, runWithTimeoutAndExit } from 'shared/utils';
import { submitGovernanceExtrinsic } from 'shared/cf_governance';

async function forceRecoverSolNonce(nonceAddress: string, nonceValue: string) {
  await submitGovernanceExtrinsic(async (chainflip) =>
    chainflip.tx.environment.forceRecoverSolNonce(
      decodeSolAddress(new PublicKey(nonceAddress).toBase58()),
      decodeSolAddress(new PublicKey(nonceValue).toBase58()),
    ),
  );
}

async function main() {
  await Promise.all([
    forceRecoverSolNonce(
      '2cNMwUCF51djw2xAiiU54wz1WrU8uG4Q8Kp8nfEuwghw',
      '8TZPeAWABEaH56pCBarps51BBfDXZxwTLXrGrdnVHMuU',
    ),
    forceRecoverSolNonce(
      'HVG21SovGzMBJDB9AQNuWb6XYq4dDZ6yUwCbRUuFnYDo',
      '9a2YpiECfkCiYPVkvBTmJv1K1e6sgQetWg8GeiJeNg2',
    ),
    forceRecoverSolNonce(
      'HDYArziNzyuNMrK89igisLrXFe78ti8cvkcxfx4qdU2p',
      'ATYZxNFThQDSo5yodfCDvh6YZtFPBZqxyvikZupQtD5v',
    ),
    forceRecoverSolNonce(
      'HLPsNyxBqfq2tLE31v6RiViLp2dTXtJRgHgsWgNDRPs2',
      'AM9PB2yZS22EShV4CQbu9mEDsWyqM44HPwQvmHUhmgyU',
    ),
    forceRecoverSolNonce(
      'GKMP63TqzbueWTrFYjRwMNkAyTHpQ54notRbAbMDmePM',
      '9FmKhHZGd1nMtYrCmvWFkXntSwGdxZAaGU3BGyAGMPxU',
    ),
    forceRecoverSolNonce(
      'EpmHm2aSPsB5ZZcDjqDhQ86h1BV32GFCbGSMuC58Y2tn',
      'AyqJtbdjRT35CmJKfaiCjL6DCe5LfRjcNRkCtNhthmgg',
    ),
    forceRecoverSolNonce(
      '9yBZNMrLrtspj4M7bEf2X6tqbqHxD2vNETw8qSdvJHMa',
      'D5ftBgbW2DQVbdRDXnU86fyF75EYjXahcFZhz2J6bQ3M',
    ),
    forceRecoverSolNonce(
      'J9dT7asYJFGS68NdgDCYjzU2Wi8uBoBusSHN1Z6JLWna',
      '3zxwonz8r5zY8c2TaFzmQfD2NTWGe8sShF4cA5eyBxLb',
    ),
    forceRecoverSolNonce(
      'GUMpVpQFNYJvSbyTtUarZVL7UDUgErKzDTSVJhekUX55',
      'H9iuxcwHporFNG9Ufx6GbMJzxKshGTXVpFYRN3BxGXhL',
    ),
    forceRecoverSolNonce(
      'AUiHYbzH7qLZSkb3u7nAqtvqC7e41sEzgWjBEvXrpfGv',
      'GoA9YN3X4dnNruw8KS8pykoziopE2iThyXypczD1JnxB',
    ),
    forceRecoverSolNonce(
      'BN2vyodNYQQTrx3gtaDAL2UGGVtZwFeF5M8krE5aYYES',
      '6M2xhGzhWQWSm1hn6SsZrSxXqwedJcvVCUU1tgb8x5gF',
    ),
    forceRecoverSolNonce(
      'Gwq9TAQCjbJtdnmtxQa3PbHFfbr6YTUBMDjEP9x2uXnH',
      '5hguE1bPSHGiHfzc3iCEL3TR1Uodk692sTDduRfb5y73',
    ),
    forceRecoverSolNonce(
      '3pGbKatko2ckoLEy139McfKiirNgy9brYxieNqFGdN1W',
      'hpFN3hwRjhx3Jdo3jTWtizbt8DvVBHBUTwKbqrxEDTU',
    ),
    forceRecoverSolNonce(
      '9Mcd8BTievK2yTvyiqG9Ft4HfDFf6mjGFBWMnCSRQP8S',
      'FfsUaqctjptQfy2LpXEprW9fHpAFpMJNDx8VxDkryto5',
    ),
    forceRecoverSolNonce(
      'AEZG74RoqM6sxf79eTizq5ShB4JTuCkMVwUgtnC8H94z',
      '6YJDJebBCgdXo6jTnHqztAxrrcVP7ARmDU532C3rvJQ3',
    ),
    forceRecoverSolNonce(
      'APLkgyCWi8DFAMF4KikjTu8YnUG1r7sMjVEfDiaBRZnS',
      'D25suHJDnB8kzBbT1zTVPqNzbSPB44ueVfGE5Fpcf7bm',
    ),
    forceRecoverSolNonce(
      '4ShNXTTHvpVt6bQdZTRdyW6yWXDzrPupdMuxajbEoGE4',
      '5SY1EquN355fvmr1Us9QF5NkgFtnpbemGRnWugpVJ1S6',
    ),
    forceRecoverSolNonce(
      'FgZp6NJYWw15U51ynfXCfU9vq3eVgDDAHMSfJ8fFBZZ8',
      'G1NKPL2YtdxCPS645sYqiRw2o93GhtXJhVsJM4WTpYPL',
    ),
    forceRecoverSolNonce(
      'ENQ9Mmg87KFLX8ncXRPDBSd7jhKCtPBi8QzAh4rkREgP',
      'EoXakeH1rPj9aU4DUuGL3AiJNkXi54H13AJVug6Fp8a4',
    ),
    forceRecoverSolNonce(
      'Hhay1UwkzkFUgrGUYuiCvUwv7kErNzAcZnVRQ2fetT7K',
      'FjsyfRZvnqssMGihxi1JDhWf8ykhyGqXp1Z38R4iR4KH',
    ),
    forceRecoverSolNonce(
      '2fUVR42opcHgGLrY1eguDXLYfQPHQe9ReJNmRorVt9v8',
      'Eqq9jnfVT3RfGZoq1VaxDwb7j3fnL7eBVunydveiEZ1t',
    ),
    forceRecoverSolNonce(
      'HfKr1wJASkW5UHs8yNWAqMeaYJdp8K2mdYwkbdVRdVrm',
      '8SmRtgVHdd6n5kqGPoo8Lj5eoBU7XrUm9ttq7HcdAeXj',
    ),
    forceRecoverSolNonce(
      'DrpYkMpJWkpNqX9yYgQfc3uZrCVYobJ3RbTABcSkHJkM',
      'EEMocPQ355GrihDWApEak8f4Bo5BWiBrWxJw16Lh51Gc',
    ),
    forceRecoverSolNonce(
      'HCXc3o2go1Y2KhfnykLYXEvofLifXTb7GT13w4GsFmGw',
      '2JH9XGSHzjpFucS1K1tVDu3ScccGDJke19Fog8umT1cB',
    ),
    forceRecoverSolNonce(
      'FFKYhae4HSnMmA6JJfe8NNtZeySA9yRWLaHzE2jqfhBr',
      'JCFTCXvAMoLLunMSKNfEtHb83Mc5H2Ruorq8kwKU2vS',
    ),
    forceRecoverSolNonce(
      'AaRrJovR9Npna4fuCJ17AB3cJAMzoNDaZymRTbGGzUZm',
      '7fPQo83ULM4g5wfGABCL2HjxMTXoAcvY7WnqQMzPU8ey',
    ),
    forceRecoverSolNonce(
      '5S8DzBBLvJUeyJccV4DekAK8KJA5PDcjwxRxCvgdyBEi',
      '6Mf4dBPMs5T8dHBzhyiQvXRYjB4HfdTBNGzWbNKihvkG',
    ),
    forceRecoverSolNonce(
      'Cot1DQZpm859brrre7swrDhTYLj2NJbg3hdMKCHk5zSk',
      'ugpSqqpQcXYybLeUumrKiDz7MJsbwvXudFFgBhVBYj8',
    ),
    forceRecoverSolNonce(
      '4mfDv7PisvtMhiyGmvD6vxRdVpB842XbUhimAZYxMEn9',
      '8MQVzBr3RvdCQ5UPrGfMyfQbPkcjrmC2TRxxknUpp17q',
    ),
    forceRecoverSolNonce(
      'BHW7qFCNHTX5QD5yJpT1hn1VM817Ji5ksZqiXMfqGrsj',
      'ihRRebrqvfSQ179gEsHzcfK8LseQNjG8qxWMzoWhPz1',
    ),
    forceRecoverSolNonce(
      'EJqZLeaxi2gVsJgQW4nbmxyWJukK25n7jB8qWKoDgWUN',
      '2hW1amHnHuRPGkhTK65sQE9ccz269XL1N6n3XgRay7BH',
    ),
    forceRecoverSolNonce(
      'BJqTPWyoqqgzhkLh1pbPh4KWBqg8kCUNzJ81avitSQrm',
      'Gd7uCmncEREuVFp2fXAQts1YDF7xNy5g7dkzTNLHKidT',
    ),
    forceRecoverSolNonce(
      'EkmPmEmSbwm8EDDYtLtaDgcfuLNtW7MbKx5w3FUpaGjv',
      '2nnJCWKtycWTs3VnNUD1BzxYJKHpMwTfuBMv3YCQKKoX',
    ),
    forceRecoverSolNonce(
      'CgwtCv8HQ67imnHEkz24TfXfyA2H5jurxcLGxAgDmNQj',
      '6y6Ja45rAWgZEdovZhKkNWxVJJ7AaQdQhM6RfPhyESqU',
    ),
    forceRecoverSolNonce(
      'zfKsXSxJ4cTpKS7S6aHL1Hy3m1CEjQuySKSwkWvukQX',
      '635q9xuqpThW4UXp7ABvTzoZfeawkHPR7tNTtGtfjdzW',
    ),
    forceRecoverSolNonce(
      '2VvN1s6txNYyBdKpaC8b6AZKVqUQiQT2Exrpa7ffCgV6',
      'ABZV1PZnrJSFMe9C8C3p9C1emgL8PVLbUXGp6wM4aGFW',
    ),
    forceRecoverSolNonce(
      'A2DT1dc4rA1uMry7WCLwoUEQQNjCAsAMkB4X9Lgo88zd',
      'GPKU2dGqWyLvHKwHWrWmscH5TEjhNcxdwwrMTPx6tLM8',
    ),
    forceRecoverSolNonce(
      '9mNBRGfTMLsSsQUn4YZfRDBVXfQ6juEWbNUTwv2ir9gC',
      '7PBYy3BaEtnP1H4j8toynDv7iJD7X8pW6tCEkBuZkfV7',
    ),
    forceRecoverSolNonce(
      '3jXiydxPx1P7Ggdja5yt384ryLJAW2c8LRGV8PPRT54C',
      'C6pejmGSjJerpJUbV3zaHYKDXDkPyAF9SJcYwsHCQ7og',
    ),
    forceRecoverSolNonce(
      '7ztGR1z28NpYjUaXyrGBzBGu62u1f9H9Pj9UVSKnT3yu',
      'FERfFzvtiQZ88x4nLyPp74XUmd45N5rneaLXrp95xWUi',
    ),
    forceRecoverSolNonce(
      '4GdnDTr5X4eJFHuzTEBLrz3tsREo8rQro7S9YDqrbMZ9',
      '2sAvRoDqKc7fwqPUReBDJFnZABHvTZS52No3prT8QBV4',
    ),
    forceRecoverSolNonce(
      'ALxnH6TBKJPBFRfFZspQkxDjb9nGLUP5oxFFdZNRFgUu',
      '4ftNy1xY73CE5Tvt2k6wP7FrkLYaKFdbqTxcTr1nHJoB',
    ),
    forceRecoverSolNonce(
      'Bu3sdWtBh5TJishgK3vneh2zJg1rjLqWN5mFTHxWspwJ',
      'CDH52v1QQFWDc2iGd44c6mR2GsRaxW7j3mU5a8iPmZxj',
    ),
    forceRecoverSolNonce(
      'GvBbUTE312RXU5iXAcNWt6CuVbfsPs5Nk28D6qvU6NF3',
      '9jEjbmo9PY1VXN5n8ynvsHTxgVgqkkyX3v37gtWLwdVL',
    ),
    forceRecoverSolNonce(
      '2LLct8SsnkW3sD9Gu8CfxmDEjKAWtFXqLvA8ymMyuq8u',
      'HPzoaZmsaiCLQh8hYcq8kAEb1n7RRmBiwznMgnHuiev9',
    ),
    forceRecoverSolNonce(
      'CQ9vUhC3dSa4LyZCpWVpNbXhSn6f7J3NQXWDDvMMk6aW',
      'DJ4ZLxfa3Rzueo9zqY2zXJRkaoJwvNRigxemAz1z5Pxm',
    ),
    forceRecoverSolNonce(
      'Cw8GqRmKzCbp7UFfafECC9sf9f936Chgx3BkbSgnXfmU',
      '13V9qLXm93RJeTChrpzpLC2bLatGKYWRqfDtYnXroVVq',
    ),
    forceRecoverSolNonce(
      'GFJ6m6YdNT1tUfAxyD2BiPSx8gwt3xe4jVAKdtdSUt8W',
      'EtNYHuALyNaWjLUSNRTppzkxc3eDntoQUwWrbfLBdvL',
    ),
    forceRecoverSolNonce(
      '7bphTuo5BKs4JJw5WPusCevmnoRk9ocFiB8EGgfwnh4c',
      'GvbiESUrxMH55onFzB3vg26JZ9KkGawNvy7Rdg2udgyE',
    ),
    forceRecoverSolNonce(
      'EFbUq18Mcdi2gGauRzmbNeD5ixaB7EYVk5JZgAF34LoS',
      '59gozJZEnmyzWKVY6HjodTfmddWyotpAWb2HiCq6xq3o',
    ),
  ]);
}

await runWithTimeoutAndExit(main(), 60);
