
// Copyright 2025 Chainflip Labs GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! Autogenerated weights for pallet_cf_lending_pools
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-08-17, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `chainflip-benchmark-runner`, CPU: `Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev-3"), DB CACHE: 1024

// Executed Command:
// ./chainflip-node
// benchmark
// pallet
// --pallet
// pallet_cf_lending_pools
// --extrinsic
// *
// --output
// state-chain/pallets/cf-lending-pools/src/weights.rs
// --steps=20
// --repeat=10
// --template=state-chain/chainflip-weight-template.hbs
// --chain=dev-3

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::ParityDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_cf_lending_pools.
pub trait WeightInfo {
	fn update_pallet_config(n: u32, ) -> Weight;
	fn add_boost_funds() -> Weight;
	fn process_deposit_as_lost(n: u32, ) -> Weight;
	fn stop_boosting() -> Weight;
	fn create_boost_pools() -> Weight;
	fn create_lending_pool() -> Weight;
	fn add_lender_funds() -> Weight;
	fn remove_lender_funds() -> Weight;
	fn request_loan() -> Weight;
	fn request_loan_with_borrowers(n: u32, ) -> Weight;
	fn expand_loan() -> Weight;
	fn make_repayment() -> Weight;
	fn usd_value_of() -> Weight;
	fn initiate_network_fee_swap() -> Weight;
	fn derive_ltv() -> Weight;
	fn loan_charge_interest() -> Weight;
	fn loan_charge_low_ltv_penalty() -> Weight;
	fn collect_pending_interest() -> Weight;
	fn start_liquidation_swaps() -> Weight;
	fn abort_liquidation_swaps() -> Weight;
	fn change_voluntary_liquidation() -> Weight;
}

/// Weights for pallet_cf_lending_pools using the Substrate node and recommended hardware.
pub struct PalletWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for PalletWeight<T> {
	/// Storage: `LendingPools::LendingConfig` (r:1 w:1)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::BoostConfig` (r:0 w:1)
	/// Proof: `LendingPools::BoostConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn update_pallet_config(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `1627`
		// Minimum execution time: 12_106_000 picoseconds.
		Weight::from_parts(10_853_355, 1627)
			// Standard Error: 2_449
			.saturating_add(Weight::from_parts(2_527_114, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::BoostConfig` (r:1 w:0)
	/// Proof: `LendingPools::BoostConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LiquidityPools::Pools` (r:1 w:0)
	/// Proof: `LiquidityPools::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::BoostPools` (r:1 w:0)
	/// Proof: `LendingPools::BoostPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::CorePools` (r:1 w:1)
	/// Proof: `LendingPools::CorePools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_boost_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1850`
		//  Estimated: `5315`
		// Minimum execution time: 95_944_000 picoseconds.
		Weight::from_parts(97_129_000, 5315)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `LendingPools::BoostedDeposits` (r:1 w:1)
	/// Proof: `LendingPools::BoostedDeposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::CorePools` (r:1 w:1)
	/// Proof: `LendingPools::CorePools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::BoostLoans` (r:1 w:1)
	/// Proof: `LendingPools::BoostLoans` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn process_deposit_as_lost(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `684 + n * (81 ±0)`
		//  Estimated: `4148 + n * (81 ±0)`
		// Minimum execution time: 35_568_000 picoseconds.
		Weight::from_parts(37_315_225, 4148)
			// Standard Error: 10_871
			.saturating_add(Weight::from_parts(655_367, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 81).saturating_mul(n.into()))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::BoostPools` (r:1 w:0)
	/// Proof: `LendingPools::BoostPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::CorePools` (r:1 w:1)
	/// Proof: `LendingPools::CorePools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn stop_boosting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4790`
		//  Estimated: `8255`
		// Minimum execution time: 91_773_000 picoseconds.
		Weight::from_parts(92_818_000, 8255)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `LendingPools::BoostPools` (r:1 w:1)
	/// Proof: `LendingPools::BoostPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::NextCorePoolId` (r:1 w:1)
	/// Proof: `LendingPools::NextCorePoolId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::CorePools` (r:0 w:1)
	/// Proof: `LendingPools::CorePools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_boost_pools() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3607`
		// Minimum execution time: 16_336_000 picoseconds.
		Weight::from_parts(16_786_000, 3607)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_lending_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3607`
		// Minimum execution time: 12_324_000 picoseconds.
		Weight::from_parts(12_739_000, 3607)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LiquidityPools::Pools` (r:1 w:0)
	/// Proof: `LiquidityPools::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_lender_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44059`
		//  Estimated: `47524`
		// Minimum execution time: 369_192_000 picoseconds.
		Weight::from_parts(381_847_000, 47524)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:1 w:0)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_lender_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44056`
		//  Estimated: `47521`
		// Minimum execution time: 432_459_000 picoseconds.
		Weight::from_parts(441_337_000, 47521)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::RefundAddresses` (r:1 w:0)
	/// Proof: `AssetBalances::RefundAddresses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::NextLoanId` (r:1 w:1)
	/// Proof: `LendingPools::NextLoanId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:2 w:1)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:3 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::PendingNetworkFees` (r:1 w:1)
	/// Proof: `LendingPools::PendingNetworkFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_loan() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45322`
		//  Estimated: `53737`
		// Minimum execution time: 519_957_000 picoseconds.
		Weight::from_parts(536_713_000, 53737)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::RefundAddresses` (r:1 w:0)
	/// Proof: `AssetBalances::RefundAddresses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::NextLoanId` (r:1 w:1)
	/// Proof: `LendingPools::NextLoanId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:52 w:1)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:5 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::PendingNetworkFees` (r:1 w:1)
	/// Proof: `LendingPools::PendingNetworkFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 50]`.
	fn request_loan_with_borrowers(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3661 + n * (282 ±0)`
		//  Estimated: `16900 + n * (2761 ±0)`
		// Minimum execution time: 185_875_000 picoseconds.
		Weight::from_parts(107_613_744, 16900)
			// Standard Error: 166_534
			.saturating_add(Weight::from_parts(33_389_655, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(15_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(5_u64))
			.saturating_add(Weight::from_parts(0, 2761).saturating_mul(n.into()))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:2 w:1)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:3 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::PendingNetworkFees` (r:1 w:1)
	/// Proof: `LendingPools::PendingNetworkFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn expand_loan() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44428`
		//  Estimated: `52843`
		// Minimum execution time: 500_815_000 picoseconds.
		Weight::from_parts(521_585_000, 52843)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:1 w:1)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LiquidityPools::Pools` (r:1 w:0)
	/// Proof: `LiquidityPools::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn make_repayment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2155`
		//  Estimated: `5620`
		// Minimum execution time: 77_814_000 picoseconds.
		Weight::from_parts(78_829_000, 5620)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn usd_value_of() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `447`
		//  Estimated: `1932`
		// Minimum execution time: 11_154_000 picoseconds.
		Weight::from_parts(11_614_000, 1932)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Swapping::SwapRequestIdCounter` (r:1 w:1)
	/// Proof: `Swapping::SwapRequestIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::SwapIdCounter` (r:1 w:1)
	/// Proof: `Swapping::SwapIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::ScheduledSwaps` (r:1 w:1)
	/// Proof: `Swapping::ScheduledSwaps` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::SwapRequests` (r:0 w:1)
	/// Proof: `Swapping::SwapRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn initiate_network_fee_swap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `137`
		//  Estimated: `1622`
		// Minimum execution time: 19_394_000 picoseconds.
		Weight::from_parts(20_260_000, 1622)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `LendingPools::GeneralLendingPools` (r:3 w:0)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn derive_ltv() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `572`
		//  Estimated: `8987`
		// Minimum execution time: 23_899_000 picoseconds.
		Weight::from_parts(24_208_000, 8987)
			.saturating_add(T::DbWeight::get().reads(3_u64))
	}
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:0)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn loan_charge_interest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `40319`
		//  Estimated: `43784`
		// Minimum execution time: 102_378_000 picoseconds.
		Weight::from_parts(106_468_000, 43784)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn loan_charge_low_ltv_penalty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `246`
		//  Estimated: `1731`
		// Minimum execution time: 6_804_000 picoseconds.
		Weight::from_parts(7_201_000, 1731)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::PendingNetworkFees` (r:1 w:1)
	/// Proof: `LendingPools::PendingNetworkFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn collect_pending_interest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `40361`
		//  Estimated: `43826`
		// Minimum execution time: 164_678_000 picoseconds.
		Weight::from_parts(167_771_000, 43826)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `LendingPools::GeneralLendingPools` (r:3 w:2)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::NetworkFee` (r:1 w:0)
	/// Proof: `Swapping::NetworkFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::NetworkFeeForAsset` (r:2 w:0)
	/// Proof: `Swapping::NetworkFeeForAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::SwapRequestIdCounter` (r:1 w:1)
	/// Proof: `Swapping::SwapRequestIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::MaximumSwapAmount` (r:2 w:0)
	/// Proof: `Swapping::MaximumSwapAmount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::MinimumChunkSize` (r:2 w:0)
	/// Proof: `Swapping::MinimumChunkSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::SwapIdCounter` (r:1 w:1)
	/// Proof: `Swapping::SwapIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::ScheduledSwaps` (r:1 w:1)
	/// Proof: `Swapping::ScheduledSwaps` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::SwapRequests` (r:0 w:4)
	/// Proof: `Swapping::SwapRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn start_liquidation_swaps() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `715`
		//  Estimated: `9130`
		// Minimum execution time: 146_049_000 picoseconds.
		Weight::from_parts(146_841_000, 9130)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: `Swapping::SwapRequests` (r:4 w:4)
	/// Proof: `Swapping::SwapRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::ScheduledSwaps` (r:1 w:1)
	/// Proof: `Swapping::ScheduledSwaps` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:2 w:2)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn abort_liquidation_swaps() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1936`
		//  Estimated: `12826`
		// Minimum execution time: 118_202_000 picoseconds.
		Weight::from_parts(119_409_000, 12826)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:1 w:1)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn change_voluntary_liquidation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2271`
		//  Estimated: `5736`
		// Minimum execution time: 45_413_000 picoseconds.
		Weight::from_parts(47_342_000, 5736)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `LendingPools::LendingConfig` (r:1 w:1)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::BoostConfig` (r:0 w:1)
	/// Proof: `LendingPools::BoostConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn update_pallet_config(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `1627`
		// Minimum execution time: 12_106_000 picoseconds.
		Weight::from_parts(10_853_355, 1627)
			// Standard Error: 2_449
			.saturating_add(Weight::from_parts(2_527_114, 0).saturating_mul(n.into()))
			.saturating_add(ParityDbWeight::get().reads(1_u64))
			.saturating_add(ParityDbWeight::get().writes(2_u64))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::BoostConfig` (r:1 w:0)
	/// Proof: `LendingPools::BoostConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LiquidityPools::Pools` (r:1 w:0)
	/// Proof: `LiquidityPools::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::BoostPools` (r:1 w:0)
	/// Proof: `LendingPools::BoostPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::CorePools` (r:1 w:1)
	/// Proof: `LendingPools::CorePools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_boost_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1850`
		//  Estimated: `5315`
		// Minimum execution time: 95_944_000 picoseconds.
		Weight::from_parts(97_129_000, 5315)
			.saturating_add(ParityDbWeight::get().reads(7_u64))
			.saturating_add(ParityDbWeight::get().writes(2_u64))
	}
	/// Storage: `LendingPools::BoostedDeposits` (r:1 w:1)
	/// Proof: `LendingPools::BoostedDeposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::CorePools` (r:1 w:1)
	/// Proof: `LendingPools::CorePools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::BoostLoans` (r:1 w:1)
	/// Proof: `LendingPools::BoostLoans` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn process_deposit_as_lost(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `684 + n * (81 ±0)`
		//  Estimated: `4148 + n * (81 ±0)`
		// Minimum execution time: 35_568_000 picoseconds.
		Weight::from_parts(37_315_225, 4148)
			// Standard Error: 10_871
			.saturating_add(Weight::from_parts(655_367, 0).saturating_mul(n.into()))
			.saturating_add(ParityDbWeight::get().reads(4_u64))
			.saturating_add(ParityDbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 81).saturating_mul(n.into()))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::BoostPools` (r:1 w:0)
	/// Proof: `LendingPools::BoostPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::CorePools` (r:1 w:1)
	/// Proof: `LendingPools::CorePools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn stop_boosting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4790`
		//  Estimated: `8255`
		// Minimum execution time: 91_773_000 picoseconds.
		Weight::from_parts(92_818_000, 8255)
			.saturating_add(ParityDbWeight::get().reads(5_u64))
			.saturating_add(ParityDbWeight::get().writes(2_u64))
	}
	/// Storage: `LendingPools::BoostPools` (r:1 w:1)
	/// Proof: `LendingPools::BoostPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::NextCorePoolId` (r:1 w:1)
	/// Proof: `LendingPools::NextCorePoolId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::CorePools` (r:0 w:1)
	/// Proof: `LendingPools::CorePools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_boost_pools() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3607`
		// Minimum execution time: 16_336_000 picoseconds.
		Weight::from_parts(16_786_000, 3607)
			.saturating_add(ParityDbWeight::get().reads(2_u64))
			.saturating_add(ParityDbWeight::get().writes(3_u64))
	}
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_lending_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3607`
		// Minimum execution time: 12_324_000 picoseconds.
		Weight::from_parts(12_739_000, 3607)
			.saturating_add(ParityDbWeight::get().reads(1_u64))
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LiquidityPools::Pools` (r:1 w:0)
	/// Proof: `LiquidityPools::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_lender_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44059`
		//  Estimated: `47524`
		// Minimum execution time: 369_192_000 picoseconds.
		Weight::from_parts(381_847_000, 47524)
			.saturating_add(ParityDbWeight::get().reads(7_u64))
			.saturating_add(ParityDbWeight::get().writes(2_u64))
	}
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:1 w:0)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_lender_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44056`
		//  Estimated: `47521`
		// Minimum execution time: 432_459_000 picoseconds.
		Weight::from_parts(441_337_000, 47521)
			.saturating_add(ParityDbWeight::get().reads(7_u64))
			.saturating_add(ParityDbWeight::get().writes(2_u64))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::RefundAddresses` (r:1 w:0)
	/// Proof: `AssetBalances::RefundAddresses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::NextLoanId` (r:1 w:1)
	/// Proof: `LendingPools::NextLoanId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:2 w:1)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:3 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::PendingNetworkFees` (r:1 w:1)
	/// Proof: `LendingPools::PendingNetworkFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_loan() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45322`
		//  Estimated: `53737`
		// Minimum execution time: 519_957_000 picoseconds.
		Weight::from_parts(536_713_000, 53737)
			.saturating_add(ParityDbWeight::get().reads(13_u64))
			.saturating_add(ParityDbWeight::get().writes(5_u64))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::RefundAddresses` (r:1 w:0)
	/// Proof: `AssetBalances::RefundAddresses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::NextLoanId` (r:1 w:1)
	/// Proof: `LendingPools::NextLoanId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:52 w:1)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:5 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::PendingNetworkFees` (r:1 w:1)
	/// Proof: `LendingPools::PendingNetworkFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 50]`.
	fn request_loan_with_borrowers(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3661 + n * (282 ±0)`
		//  Estimated: `16900 + n * (2761 ±0)`
		// Minimum execution time: 185_875_000 picoseconds.
		Weight::from_parts(107_613_744, 16900)
			// Standard Error: 166_534
			.saturating_add(Weight::from_parts(33_389_655, 0).saturating_mul(n.into()))
			.saturating_add(ParityDbWeight::get().reads(15_u64))
			.saturating_add(ParityDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(ParityDbWeight::get().writes(5_u64))
			.saturating_add(Weight::from_parts(0, 2761).saturating_mul(n.into()))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:2 w:1)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:3 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::PendingNetworkFees` (r:1 w:1)
	/// Proof: `LendingPools::PendingNetworkFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn expand_loan() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `44428`
		//  Estimated: `52843`
		// Minimum execution time: 500_815_000 picoseconds.
		Weight::from_parts(521_585_000, 52843)
			.saturating_add(ParityDbWeight::get().reads(11_u64))
			.saturating_add(ParityDbWeight::get().writes(4_u64))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:1 w:1)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LiquidityPools::Pools` (r:1 w:0)
	/// Proof: `LiquidityPools::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AssetBalances::FreeBalances` (r:1 w:1)
	/// Proof: `AssetBalances::FreeBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn make_repayment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2155`
		//  Estimated: `5620`
		// Minimum execution time: 77_814_000 picoseconds.
		Weight::from_parts(78_829_000, 5620)
			.saturating_add(ParityDbWeight::get().reads(7_u64))
			.saturating_add(ParityDbWeight::get().writes(3_u64))
	}
	/// Storage: `GenericElections::ElectoralUnsynchronisedState` (r:1 w:0)
	/// Proof: `GenericElections::ElectoralUnsynchronisedState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn usd_value_of() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `447`
		//  Estimated: `1932`
		// Minimum execution time: 11_154_000 picoseconds.
		Weight::from_parts(11_614_000, 1932)
			.saturating_add(ParityDbWeight::get().reads(1_u64))
	}
	/// Storage: `Swapping::SwapRequestIdCounter` (r:1 w:1)
	/// Proof: `Swapping::SwapRequestIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::SwapIdCounter` (r:1 w:1)
	/// Proof: `Swapping::SwapIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::ScheduledSwaps` (r:1 w:1)
	/// Proof: `Swapping::ScheduledSwaps` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::SwapRequests` (r:0 w:1)
	/// Proof: `Swapping::SwapRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn initiate_network_fee_swap() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `137`
		//  Estimated: `1622`
		// Minimum execution time: 19_394_000 picoseconds.
		Weight::from_parts(20_260_000, 1622)
			.saturating_add(ParityDbWeight::get().reads(3_u64))
			.saturating_add(ParityDbWeight::get().writes(4_u64))
	}
	/// Storage: `LendingPools::GeneralLendingPools` (r:3 w:0)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn derive_ltv() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `572`
		//  Estimated: `8987`
		// Minimum execution time: 23_899_000 picoseconds.
		Weight::from_parts(24_208_000, 8987)
			.saturating_add(ParityDbWeight::get().reads(3_u64))
	}
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:0)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn loan_charge_interest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `40319`
		//  Estimated: `43784`
		// Minimum execution time: 102_378_000 picoseconds.
		Weight::from_parts(106_468_000, 43784)
			.saturating_add(ParityDbWeight::get().reads(2_u64))
	}
	/// Storage: `LendingPools::LendingConfig` (r:1 w:0)
	/// Proof: `LendingPools::LendingConfig` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn loan_charge_low_ltv_penalty() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `246`
		//  Estimated: `1731`
		// Minimum execution time: 6_804_000 picoseconds.
		Weight::from_parts(7_201_000, 1731)
			.saturating_add(ParityDbWeight::get().reads(1_u64))
	}
	/// Storage: `LendingPools::GeneralLendingPools` (r:1 w:1)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::PendingNetworkFees` (r:1 w:1)
	/// Proof: `LendingPools::PendingNetworkFees` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn collect_pending_interest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `40361`
		//  Estimated: `43826`
		// Minimum execution time: 164_678_000 picoseconds.
		Weight::from_parts(167_771_000, 43826)
			.saturating_add(ParityDbWeight::get().reads(2_u64))
			.saturating_add(ParityDbWeight::get().writes(2_u64))
	}
	/// Storage: `LendingPools::GeneralLendingPools` (r:3 w:2)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::NetworkFee` (r:1 w:0)
	/// Proof: `Swapping::NetworkFee` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::NetworkFeeForAsset` (r:2 w:0)
	/// Proof: `Swapping::NetworkFeeForAsset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::SwapRequestIdCounter` (r:1 w:1)
	/// Proof: `Swapping::SwapRequestIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::MaximumSwapAmount` (r:2 w:0)
	/// Proof: `Swapping::MaximumSwapAmount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::MinimumChunkSize` (r:2 w:0)
	/// Proof: `Swapping::MinimumChunkSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::SwapIdCounter` (r:1 w:1)
	/// Proof: `Swapping::SwapIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::ScheduledSwaps` (r:1 w:1)
	/// Proof: `Swapping::ScheduledSwaps` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::SwapRequests` (r:0 w:4)
	/// Proof: `Swapping::SwapRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn start_liquidation_swaps() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `715`
		//  Estimated: `9130`
		// Minimum execution time: 146_049_000 picoseconds.
		Weight::from_parts(146_841_000, 9130)
			.saturating_add(ParityDbWeight::get().reads(13_u64))
			.saturating_add(ParityDbWeight::get().writes(9_u64))
	}
	/// Storage: `Swapping::SwapRequests` (r:4 w:4)
	/// Proof: `Swapping::SwapRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Swapping::ScheduledSwaps` (r:1 w:1)
	/// Proof: `Swapping::ScheduledSwaps` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::GeneralLendingPools` (r:2 w:2)
	/// Proof: `LendingPools::GeneralLendingPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn abort_liquidation_swaps() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1936`
		//  Estimated: `12826`
		// Minimum execution time: 118_202_000 picoseconds.
		Weight::from_parts(119_409_000, 12826)
			.saturating_add(ParityDbWeight::get().reads(7_u64))
			.saturating_add(ParityDbWeight::get().writes(7_u64))
	}
	/// Storage: `AccountRoles::AccountRoles` (r:1 w:0)
	/// Proof: `AccountRoles::AccountRoles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Environment::RuntimeSafeMode` (r:1 w:0)
	/// Proof: `Environment::RuntimeSafeMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `LendingPools::LoanAccounts` (r:1 w:1)
	/// Proof: `LendingPools::LoanAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn change_voluntary_liquidation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2271`
		//  Estimated: `5736`
		// Minimum execution time: 45_413_000 picoseconds.
		Weight::from_parts(47_342_000, 5736)
			.saturating_add(ParityDbWeight::get().reads(3_u64))
			.saturating_add(ParityDbWeight::get().writes(1_u64))
	}
}
