name: "Run Benchmarks"
on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Which Commit SHA should we get the binaries from?"
        required: true
        type: string
      base_branch_name:
        description: "Which Branch should the Results PR be opened against?"
        required: true
        type: string
      steps:
        description: "How many steps should we run?"
        required: false
        type: string
        default: "20"
      repetitions:
        description: "How many times should we repeat each step?"
        required: false
        type: string
        default: "10"
      benchmark_machine_spec:
        description: "What machine Spec the benchmark will run on?"
        required: true
        default: 4vCPU-8GB
        type: choice
        options:
          - 4vCPU-8GB
          - 4vCPU-16GB
      profile:
        description: "Which profile should we use?"
        required: false
        type: choice
        options:
          - production
          - release
      binary_artefact_source:
        description: "Which source should we use for the binary artefact?"
        required: false
        type: choice
        options:
          - main
          - release
        default: release

env:
  FORCE_COLOR: 1

jobs:
  deploy_benchmarks_runner:
    uses: ./.github/workflows/_110_deploy_benchmarks_runner.yml
    with:
      command: apply
      benchmark_machine_spec: ${{ inputs.benchmark_machine_spec }}
    secrets: inherit

  run_benchmarks:
    permissions:
      contents: write
      pull-requests: write
    runs-on:
      [
        self-hosted,
        linux,
        x64,
        "${{ github.event.inputs.benchmark_machine_spec }}",
      ]
    needs: [deploy_benchmarks_runner]
    continue-on-error: true
    timeout-minutes: 40
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Resolve full commit SHA
        id: resolve-sha
        run: |
          FULL_SHA=$(git rev-parse "${{ inputs.commit_sha }}")
          echo "full_sha=$FULL_SHA" >> "$GITHUB_OUTPUT"

      - name: Fetch chainflip-node with benchmarks from ${{ inputs.commit_sha }}
        uses: dawidd6/action-download-artifact@fe9d59ce33ce92db8a6ac90b2c8be6b6d90417c8
        with:
          workflow: ci-benchmarks-${{ inputs.binary_artefact_source }}.yml
          workflow_conclusion: completed
          name: chainflip-node-ubuntu-benchmarks-${{ inputs.profile }}
          commit: ${{ steps.resolve-sha.outputs.full_sha }}
          github_token: ${{ secrets.CF_BACKEND_GITHUB_TOKEN }}
          search_artifacts: true
          check_artifacts: true

      - name: Update permissions on chainflip-node 🚓
        run: chmod +x ./chainflip-node

      - name: Run benchmarks 📏
        run: >
          ./state-chain/scripts/benchmark-all.sh
          --binary ./chainflip-node
          --steps ${{ github.event.inputs.steps }}
          --repetitions ${{ github.event.inputs.repetitions }}

      - name: Cleanup 🧹
        run: >
          rm ./chainflip-node

      - name: Setup Git 🛠️
        uses: ./.github/actions/setup-git
        with:
          ssh-private-key: ${{ secrets.CF_GITHUB_BOT_SSH_PRIVATE_KEY }}

      - name: Make a pull request with the changed weight files 🕯️
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          base: ${{ inputs.base_branch_name }}
          title: "[AUTOMATED] Benchmark results"
          commit-message: "[AUTOMATED] Benchmarking results."
          body: "This pull request was opened automatically. Close it if you think it was opened in error."
          branch: auto/benchmark-results/${{ inputs.commit_sha }}
          delete-branch: true
          token: ${{ secrets.CF_BACKEND_GITHUB_TOKEN }}

  destroy_benchmarks_runner:
    needs: [run_benchmarks]
    uses: ./.github/workflows/_110_deploy_benchmarks_runner.yml
    with:
      command: destroy
      benchmark_machine_spec: ${{ inputs.benchmark_machine_spec }}
    secrets: inherit
