name: Build chainflip-node with benchmarks for main
on:
  push:
    branches:
      - main

jobs:
  sfw-check:
    uses: ./.github/workflows/_00_sfw_check.yml
  run-benchmarks-main:
    needs: [sfw-check]
    uses: ./.github/workflows/_27_benchmarks.yml
    secrets: inherit
    with:
      ci-runner: "rust-builder"
