name: Build chainflip-node with benchmarks for release branches
on:
  push:
    branches:
      - release/*

jobs:
  sfw-check:
    uses: ./.github/workflows/_00_sfw_check.yml
  run-benchmarks-release:
    needs: [sfw-check]
    uses: ./.github/workflows/_27_benchmarks.yml
    secrets: inherit
    with:
      ci-runner: "rust-builder-light-no-cache"
